masync: pthread memcpy with FIFO queue to ringbuffer
pmem/miniasync pull request #33
Opened 2021-12-31 08:49 UTC by blazej-smorawski

2022-01-10 14:34 UTC, pbalcer requested changes
> Reviewed 19 of 29 files at r2, 14 of 14 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/miniasync/33)* status: all files reviewed, 13 unresolved discussions (waiting on @blazej-smorawski)

___
*[doc/miniasync_vdm.3.md.in, line 62 at r3](https://reviewable.io/reviews/pmem/miniasync/33#-Mt3B-pVAbn0joFgKVRo:-Mt3B-pVAbn0joFgKVRp:b-pnnfxi) ([raw file](https://github.com/pmem/miniasync/blob/a1c0158cc17e30110f7edcc98c4d86b117a7d636/doc/miniasync_vdm.3.md.in#L62)):*
> ```
> ```
> From now on, every future created with `vdm_memcpy` and previously
> created instanece of data mover `struct vdm_memcpy_future fut = vdm_memcpy(vdm, dst, src, size, flags);`
> ```

instance
___
*[doc/miniasync_vdm.3.md.in, line 65 at r3](https://reviewable.io/reviews/pmem/miniasync/33#-Mt3BCSZ81ISSqp_Prlv:-Mt3BCSZ81ISSqp_Prlw:b-v0v8i7) ([raw file](https://github.com/pmem/miniasync/blob/a1c0158cc17e30110f7edcc98c4d86b117a7d636/doc/miniasync_vdm.3.md.in#L65)):*
> ```
> will be performed asynchronously.
> When a new memcpy is processed by runtime, the runtime in every `future_poll`
> tries until it succeeds to add it's context into a queue, which is dequeued, regarding the policy set in
> ```

This sentence doesn't parse (it isn't legible).

Runtime is not important here. It might not exist. Simply say that every time a future is polled, it tries to enqueue a memcpy operation until successful. Once that's done, a separate background thread dequeues and processes those operations. 
___
*[doc/miniasync_vdm.3.md.in, line 67 at r3](https://reviewable.io/reviews/pmem/miniasync/33#-Mt3Bzx4DFIB3AiR8yu4:-Mt3Bzx4DFIB3AiR8yu5:b4ffoka) ([raw file](https://github.com/pmem/miniasync/blob/a1c0158cc17e30110f7edcc98c4d86b117a7d636/doc/miniasync_vdm.3.md.in#L67)):*
> ```
> tries until it succeeds to add it's context into a queue, which is dequeued, regarding the policy set in
> `struct vdm_pthread_queue`, into a ringbuffer. The ringbuffer is containing
> multiple memcpy_pthreads data and is dequeued by worker threads in FIFO order.
> ```

"the ring buffer contains"

this sounds like an implementation detail.
___
*[doc/miniasync_vdm.3.md.in, line 69 at r3](https://reviewable.io/reviews/pmem/miniasync/33#-Mt3C8FQ1rxJlAnCLHA2:-Mt3C8FQ1rxJlAnCLHA3:b-8xczxy) ([raw file](https://github.com/pmem/miniasync/blob/a1c0158cc17e30110f7edcc98c4d86b117a7d636/doc/miniasync_vdm.3.md.in#L69)):*
> ```
> multiple memcpy_pthreads data and is dequeued by worker threads in FIFO order.
> If you would like to change the count of worker threads, ringbuffer or queue size, go to
> `vdm.h` and change the values of the appropriate preprocessor directives which
> ```

Library users should never have to modify installed external headers. The number of worker threads and/or the policy should be a parameter for some function that instantiates this specific mover. (I just realized that there's no straightforward way to do that - we should probably just delete the vdm_new/vdm_delete functions as we talked about earlier today, and then every mover would just have its own instantiation method).
___
*[examples/basic-async/basic-async.c, line 9 at r3](https://reviewable.io/reviews/pmem/miniasync/33#-Mt3DdIj5JPGow38nhwd:-Mt3DdIj5JPGow38nhwe:bb7qk9l) ([raw file](https://github.com/pmem/miniasync/blob/a1c0158cc17e30110f7edcc98c4d86b117a7d636/examples/basic-async/basic-async.c#L9)):*
> ```C
> 
> int
> main()
> ```

void
___
*[examples/basic-async/basic-async.c, line 16 at r3](https://reviewable.io/reviews/pmem/miniasync/33#-Mt3Dv7j5WDwberQhBr1:-Mt3Dv7j5WDwberQhBr2:b-bri561) ([raw file](https://github.com/pmem/miniasync/blob/a1c0158cc17e30110f7edcc98c4d86b117a7d636/examples/basic-async/basic-async.c#L16)):*
> ```C
> 	struct vdm *vdm = vdm_new(vdm_async_descriptor);
> 
> 	for (int i = 0; i < 10; i++) {
> ```

I don't like this - too much copy/paste. I suggest using arrays of futures/data instead.
___
*[src/runtime.c, line 82 at r3](https://reviewable.io/reviews/pmem/miniasync/33#-Mt3EPtW4RQh4PPzjuoB:-Mt3EPtW4RQh4PPzjuoC:bb7r2f0) ([raw file](https://github.com/pmem/miniasync/blob/f8935072bc797e8244f1b17427c7aa796dbfd4b8/src/runtime.c#L82)):*
> ```C
> 		for (uint64_t i = 0; i < runtime->spins_before_sleep; ++i) {
> 			for (uint64_t f = 0; f < nfuts; ++f) {
> 				struct future *fut = futs[f];
> ```

why?
___
*[src/vdm.c, line 118 at r3](https://reviewable.io/reviews/pmem/miniasync/33#-Mt3EdyR-AfHMdTLucAR:-Mt3EdyR-AfHMdTLucAS:b6oe1qy) ([raw file](https://github.com/pmem/miniasync/blob/a1c0158cc17e30110f7edcc98c4d86b117a7d636/src/vdm.c#L118)):*
> ```C
> 	util_atomic_load64(&data->started, &started);
> 	util_atomic_load64(&data->complete, &complete);
> 	return (complete) ? FUTURE_STATE_COMPLETE :
> ```

change this into:
```
if (complete) return FUTURE_STATE_COMPLETE;
if (started) return FUTURE_STATE_RUNNING;
return FUTURE_STATE_IDLE;
```
___
*[src/vdm.c, line 145 at r3](https://reviewable.io/reviews/pmem/miniasync/33#-Mt3JWxN0uU1ZA63qDt7:-Mt3JWxN0uU1ZA63qDt8:b-numlen) ([raw file](https://github.com/pmem/miniasync/blob/a1c0158cc17e30110f7edcc98c4d86b117a7d636/src/vdm.c#L145)):*
> ```C
> 
> void
> vdm_pthread_init(void **vdm_data)
> ```

It's too big - move this to its own set of files.
___
*[src/vdm.c, line 148 at r3](https://reviewable.io/reviews/pmem/miniasync/33#-Mt3J_fh8FJgPtZXWRQo:-Mt3J_fh8FJgPtZXWRQp:b-sll0mr) ([raw file](https://github.com/pmem/miniasync/blob/a1c0158cc17e30110f7edcc98c4d86b117a7d636/src/vdm.c#L148)):*
> ```C
> {
> 	struct vdm_pthread_data *pthread_data =
> 		malloc(sizeof(struct vdm_pthread_data));
> ```

check for malloc failures
___
*[src/vdm.c, line 266 at r3](https://reviewable.io/reviews/pmem/miniasync/33#-Mt3OcoB8QDX37FntNVI:-Mt3OcoB8QDX37FntNVJ:b-5jhtyp) ([raw file](https://github.com/pmem/miniasync/blob/a1c0158cc17e30110f7edcc98c4d86b117a7d636/src/vdm.c#L266)):*
> ```C
> 		 */
> 		os_mutex_lock(&pthread_data->lock);
> 		while ((data = ringbuf_trydequeue(buf)) == NULL) {
> ```

ringbuf_dequeue will wait until something shows up. No need to use additional condition variables.
___
*[src/vdm.c, line 283 at r3](https://reviewable.io/reviews/pmem/miniasync/33#-Mt3OEyW0wqQncY8CVaz:-Mt3OEyW0wqQncY8CVb-:b-995ksn) ([raw file](https://github.com/pmem/miniasync/blob/a1c0158cc17e30110f7edcc98c4d86b117a7d636/src/vdm.c#L283)):*
> ```C
> 
> void *
> vdm_pthread_queue_loop(void *arg)
> ```

What's the reason for this intermediate thread? It's safe to enqueue to the ring buffer from multiple threads.
___
*[src/include/libminiasync/vdm.h, line 62 at r3](https://reviewable.io/reviews/pmem/miniasync/33#-Mt3P7wa30dVq7ttI1ta:-Mt3P7wa30dVq7ttI1tb:bqfby23) ([raw file](https://github.com/pmem/miniasync/blob/a1c0158cc17e30110f7edcc98c4d86b117a7d636/src/include/libminiasync/vdm.h#L62)):*
> ```objc
> };
> 
> struct vdm_pthread_queue {
> ```

this is a public header and these are private structures. Move them to the C file.


<!-- Sent from Reviewable.io -->

2022-01-11 07:00 UTC, blazej-smorawski reviewed
> Reviewed 2 of 14 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/miniasync/33)* status: all files reviewed, 13 unresolved discussions (waiting on @blazej-smorawski and @pbalcer)

___
*[doc/miniasync_vdm.3.md.in, line 62 at r3](https://reviewable.io/reviews/pmem/miniasync/33#-Mt3B-pVAbn0joFgKVRo:-Mt3dGjV0eGA2qXdS42F:b-896fix) ([raw file](https://github.com/pmem/miniasync/blob/a1c0158cc17e30110f7edcc98c4d86b117a7d636/doc/miniasync_vdm.3.md.in#L62)):*
<details><summary><i>Previously, pbalcer (Piotr Balcer) wrote…</i></summary><blockquote>

instance
</blockquote></details>

Done.
___
*[doc/miniasync_vdm.3.md.in, line 65 at r3](https://reviewable.io/reviews/pmem/miniasync/33#-Mt3BCSZ81ISSqp_Prlv:-Mt3ecEUCbxPd9UnS2J3:b-896fix) ([raw file](https://github.com/pmem/miniasync/blob/a1c0158cc17e30110f7edcc98c4d86b117a7d636/doc/miniasync_vdm.3.md.in#L65)):*
<details><summary><i>Previously, pbalcer (Piotr Balcer) wrote…</i></summary><blockquote>

This sentence doesn't parse (it isn't legible).

Runtime is not important here. It might not exist. Simply say that every time a future is polled, it tries to enqueue a memcpy operation until successful. Once that's done, a separate background thread dequeues and processes those operations. 

</blockquote></details>

Done.
___
*[doc/miniasync_vdm.3.md.in, line 67 at r3](https://reviewable.io/reviews/pmem/miniasync/33#-Mt3Bzx4DFIB3AiR8yu4:-Mt3eW94-FqEOM0GqBzd:b-896fix) ([raw file](https://github.com/pmem/miniasync/blob/a1c0158cc17e30110f7edcc98c4d86b117a7d636/doc/miniasync_vdm.3.md.in#L67)):*
<details><summary><i>Previously, pbalcer (Piotr Balcer) wrote…</i></summary><blockquote>

"the ring buffer contains"

this sounds like an implementation detail.
</blockquote></details>

Done.
___
*[doc/miniasync_vdm.3.md.in, line 69 at r3](https://reviewable.io/reviews/pmem/miniasync/33#-Mt3C8FQ1rxJlAnCLHA2:-Mt3csigB2F475hqIIuI:bmogvqb) ([raw file](https://github.com/pmem/miniasync/blob/a1c0158cc17e30110f7edcc98c4d86b117a7d636/doc/miniasync_vdm.3.md.in#L69)):*
<details><summary><i>Previously, pbalcer (Piotr Balcer) wrote…</i></summary><blockquote>

Library users should never have to modify installed external headers. The number of worker threads and/or the policy should be a parameter for some function that instantiates this specific mover. (I just realized that there's no straightforward way to do that - we should probably just delete the vdm_new/vdm_delete functions as we talked about earlier today, and then every mover would just have its own instantiation method).
</blockquote></details>

Sure, it was just a quick and dirty way of setting those values for testing purposes, because I did not want to go too deep into modifying the existing code. 
___
*[examples/basic-async/basic-async.c, line 9 at r3](https://reviewable.io/reviews/pmem/miniasync/33#-Mt3DdIj5JPGow38nhwd:-Mt3eiQr41WThU70F-AH:b-896fix) ([raw file](https://github.com/pmem/miniasync/blob/a1c0158cc17e30110f7edcc98c4d86b117a7d636/examples/basic-async/basic-async.c#L9)):*
<details><summary><i>Previously, pbalcer (Piotr Balcer) wrote…</i></summary><blockquote>

void
</blockquote></details>

Done.
___
*[examples/basic-async/basic-async.c, line 16 at r3](https://reviewable.io/reviews/pmem/miniasync/33#-Mt3Dv7j5WDwberQhBr1:-Mt6lxSr5WzeRTzCsFyL:b-7yvxjd) ([raw file](https://github.com/pmem/miniasync/blob/a1c0158cc17e30110f7edcc98c4d86b117a7d636/examples/basic-async/basic-async.c#L16)):*
<details><summary><i>Previously, pbalcer (Piotr Balcer) wrote…</i></summary><blockquote>

I don't like this - too much copy/paste. I suggest using arrays of futures/data instead.
</blockquote></details>

Ok, I left only two memcpy's in the example, so it looks simpler. Usage of an array of futures is already in memcpy_async test.
___
*[src/runtime.c, line 82 at r3](https://reviewable.io/reviews/pmem/miniasync/33#-Mt3EPtW4RQh4PPzjuoB:-Mt3f-s36R6-V1taBz52:b8xgh85) ([raw file](https://github.com/pmem/miniasync/blob/f8935072bc797e8244f1b17427c7aa796dbfd4b8/src/runtime.c#L82)):*
<details><summary><i>Previously, pbalcer (Piotr Balcer) wrote…</i></summary><blockquote>

why?
</blockquote></details>

Forgot to revert this change after troubleshooting.
___
*[src/vdm.c, line 118 at r3](https://reviewable.io/reviews/pmem/miniasync/33#-Mt3EdyR-AfHMdTLucAR:-Mt3f_e2-RTECsuvfGRY:b-896fix) ([raw file](https://github.com/pmem/miniasync/blob/a1c0158cc17e30110f7edcc98c4d86b117a7d636/src/vdm.c#L118)):*
<details><summary><i>Previously, pbalcer (Piotr Balcer) wrote…</i></summary><blockquote>

change this into:
```
if (complete) return FUTURE_STATE_COMPLETE;
if (started) return FUTURE_STATE_RUNNING;
return FUTURE_STATE_IDLE;
```
</blockquote></details>

Done.
___
*[src/vdm.c, line 148 at r3](https://reviewable.io/reviews/pmem/miniasync/33#-Mt3J_fh8FJgPtZXWRQo:-Mt6v3jW-yG3LQW0h_QK:b-896fix) ([raw file](https://github.com/pmem/miniasync/blob/a1c0158cc17e30110f7edcc98c4d86b117a7d636/src/vdm.c#L148)):*
<details><summary><i>Previously, pbalcer (Piotr Balcer) wrote…</i></summary><blockquote>

check for malloc failures
</blockquote></details>

Done.
___
*[src/vdm.c, line 266 at r3](https://reviewable.io/reviews/pmem/miniasync/33#-Mt3OcoB8QDX37FntNVI:-Mt6vVdNAsxSzKVHJh09:b-xcvvv0) ([raw file](https://github.com/pmem/miniasync/blob/a1c0158cc17e30110f7edcc98c4d86b117a7d636/src/vdm.c#L266)):*
<details><summary><i>Previously, pbalcer (Piotr Balcer) wrote…</i></summary><blockquote>

ringbuf_dequeue will wait until something shows up. No need to use additional condition variables.
</blockquote></details>

Ok, I will do that.
___
*[src/vdm.c, line 283 at r3](https://reviewable.io/reviews/pmem/miniasync/33#-Mt3OEyW0wqQncY8CVaz:-Mt3hJ7pDBvlWoJqCpJV:b9ofi91) ([raw file](https://github.com/pmem/miniasync/blob/a1c0158cc17e30110f7edcc98c4d86b117a7d636/src/vdm.c#L283)):*
<details><summary><i>Previously, pbalcer (Piotr Balcer) wrote…</i></summary><blockquote>

What's the reason for this intermediate thread? It's safe to enqueue to the ring buffer from multiple threads.
</blockquote></details>

My idea, was that all tasks in the ring-buffer are equal, but we can decide which tasks go first to it. So for example - we could add shortest tasks first to the ring-buffer.
___
*[src/include/libminiasync/vdm.h, line 62 at r3](https://reviewable.io/reviews/pmem/miniasync/33#-Mt3P7wa30dVq7ttI1ta:-Mt3ioat9tDetdtRVtGO:b-896fix) ([raw file](https://github.com/pmem/miniasync/blob/a1c0158cc17e30110f7edcc98c4d86b117a7d636/src/include/libminiasync/vdm.h#L62)):*
<details><summary><i>Previously, pbalcer (Piotr Balcer) wrote…</i></summary><blockquote>

this is a public header and these are private structures. Move them to the C file.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-01-11 07:12 UTC, blazej-smorawski reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/miniasync/33)* status: all files reviewed, 13 unresolved discussions (waiting on @blazej-smorawski and @pbalcer)

___
*[examples/basic-async/basic-async.c, line 9 at r3](https://reviewable.io/reviews/pmem/miniasync/33#-Mt3DdIj5JPGow38nhwd:-Mt6yZS66tIGMlwxdPD5:b-brhwhp) ([raw file](https://github.com/pmem/miniasync/blob/a1c0158cc17e30110f7edcc98c4d86b117a7d636/examples/basic-async/basic-async.c#L9)):*
<details><summary><i>Previously, blazej-smorawski wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Using `void main` throws a warning treated as an error that it should return an `int`. 
___
*[src/vdm.c, line 266 at r3](https://reviewable.io/reviews/pmem/miniasync/33#-Mt3OcoB8QDX37FntNVI:-Mt6xZvB3aBSP2KV_8fT:b-896fix) ([raw file](https://github.com/pmem/miniasync/blob/a1c0158cc17e30110f7edcc98c4d86b117a7d636/src/vdm.c#L266)):*
<details><summary><i>Previously, blazej-smorawski wrote…</i></summary><blockquote>

Ok, I will do that.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-01-11 08:38 UTC, pbalcer requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/miniasync/33)* status: 26 of 33 files reviewed, 13 unresolved discussions (waiting on @blazej-smorawski and @pbalcer)

___
*[examples/basic-async/basic-async.c, line 9 at r3](https://reviewable.io/reviews/pmem/miniasync/33#-Mt3DdIj5JPGow38nhwd:-Mt7HTBH0rdzBUPp7hSl:b8rurug) ([raw file](https://github.com/pmem/miniasync/blob/a1c0158cc17e30110f7edcc98c4d86b117a7d636/examples/basic-async/basic-async.c#L9)):*
<details><summary><i>Previously, blazej-smorawski wrote…</i></summary><blockquote>

Using `void main` throws a warning treated as an error that it should return an `int`. 
</blockquote></details>

That's not what I meant.

http://www.open-std.org/jtc1/sc22/wg14/www/docs/n1256.pdf
5.1.2.2.1


<!-- Sent from Reviewable.io -->

2022-01-11 09:48 UTC, DamianDuy commented on src/vdm.c
> +	pthread_data->threads = malloc(sizeof(pthread_t) * THREADS_COUNT);
Could the ```sizeof(pthread_t)``` here be safely changed to ```sizeof(os_thread_t)```?

2022-01-11 12:18 UTC, blazej-smorawski reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/miniasync/33)* status: 26 of 33 files reviewed, 14 unresolved discussions (waiting on @blazej-smorawski, @DamianDuy, and @pbalcer)

___
*[examples/basic-async/basic-async.c, line 9 at r3](https://reviewable.io/reviews/pmem/miniasync/33#-Mt3DdIj5JPGow38nhwd:-Mt82sNA8Hj3QPpns4yt:b-896fix) ([raw file](https://github.com/pmem/miniasync/blob/a1c0158cc17e30110f7edcc98c4d86b117a7d636/examples/basic-async/basic-async.c#L9)):*
<details><summary><i>Previously, pbalcer (Piotr Balcer) wrote…</i></summary><blockquote>

That's not what I meant.

http://www.open-std.org/jtc1/sc22/wg14/www/docs/n1256.pdf
5.1.2.2.1
</blockquote></details>

Done.
___
*[src/vdm.c, line 225 at r4](https://reviewable.io/reviews/pmem/miniasync/33#-MsEfSvFE6Zl5940pL-3-r4-225:-Mt82v-iC5s_bPUcew90:b-np4iwv) ([raw file](https://github.com/pmem/miniasync/blob/093a8a9bb069b0f8daae5cb79b633ca7e8e8d602/src/vdm.c#L225)):*
<details><summary><i>Previously, DamianDuy (Damian Duy) wrote…</i></summary><blockquote>

Could the ```sizeof(pthread_t)``` here be safely changed to ```sizeof(os_thread_t)```?
</blockquote></details>

My bad, fixed it here and a few lines bellow.


<!-- Sent from Reviewable.io -->

2022-01-11 13:53 UTC, blazej-smorawski reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/miniasync/33)* status: 26 of 33 files reviewed, 14 unresolved discussions (waiting on @blazej-smorawski, @DamianDuy, and @pbalcer)

___
*[src/vdm.c, line 145 at r3](https://reviewable.io/reviews/pmem/miniasync/33#-Mt3JWxN0uU1ZA63qDt7:-Mt8PSs72_08bX2W6-m9:b-896fix) ([raw file](https://github.com/pmem/miniasync/blob/a1c0158cc17e30110f7edcc98c4d86b117a7d636/src/vdm.c#L145)):*
<details><summary><i>Previously, pbalcer (Piotr Balcer) wrote…</i></summary><blockquote>

It's too big - move this to its own set of files.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-01-12 14:58 UTC, pbalcer requested changes
> Reviewed 2 of 7 files at r4, 10 of 12 files at r5, 19 of 19 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/miniasync/33)* status: 35 of 37 files reviewed, 11 unresolved discussions (waiting on @blazej-smorawski and @pbalcer)

___
*[doc/miniasync_vdm.3.md.in, line 65 at r3](https://reviewable.io/reviews/pmem/miniasync/33#-Mt3BCSZ81ISSqp_Prlv:-MtDjq0r3If_abMUkbBG:b-23hqo3) ([raw file](https://github.com/pmem/miniasync/blob/a1c0158cc17e30110f7edcc98c4d86b117a7d636/doc/miniasync_vdm.3.md.in#L65)):*
<details><summary><i>Previously, blazej-smorawski wrote…</i></summary><blockquote>

Done.
</blockquote></details>

you made typos ;)
`the queue is dequeued` looks odd.
___
*[examples/basic-async/basic-async.c, line 9 at r3](https://reviewable.io/reviews/pmem/miniasync/33#-Mt3DdIj5JPGow38nhwd:-MtDk_7E-l-SXa_fq2kf:b3fmry6) ([raw file](https://github.com/pmem/miniasync/blob/a1c0158cc17e30110f7edcc98c4d86b117a7d636/examples/basic-async/basic-async.c#L9)):*
<details><summary><i>Previously, blazej-smorawski wrote…</i></summary><blockquote>

Done.
</blockquote></details>

no?

int
main(void)
{
}
___
*[src/vdm.c, line 7 at r6](https://reviewable.io/reviews/pmem/miniasync/33#-MtDlg7vCCPtj1SIrJsA:-MtDlg7vCCPtj1SIrJsB:b-z8ybb8) ([raw file](https://github.com/pmem/miniasync/blob/1c48587e8f60014570ec7c6b61319bf1cd3d5848/src/vdm.c#L7)):*
> ```C
> #include <string.h>
> #include "libminiasync/vdm.h"
> #include "libminiasync/vdm_threads.h"
> ```

just move the entire descriptor out of this file. This shouldn't have to pull in this header.
___
*[src/vdm.c, line 32 at r6](https://reviewable.io/reviews/pmem/miniasync/33#-MtDkzEz6lMUjZJoK8rv:-MtDkzEz6lMUjZJoK8rw:bgkb4au) ([raw file](https://github.com/pmem/miniasync/blob/1c48587e8f60014570ec7c6b61319bf1cd3d5848/src/vdm.c#L32)):*
> ```C
> 	if (descriptor->vdm_data_init) {
> 		descriptor->vdm_data_init(&vdm->data);
> 		if (!vdm->data) {
> ```

why?
If you want to make the `vdm_data_init` fallible just change the function type to something that returns an int and check if the ret value is 0 (so `if (vdm_data_init(...) != 0) err;`) 
___
*[src/vdm.c, line 64 at r6](https://reviewable.io/reviews/pmem/miniasync/33#-MtDlHTPBQJVSH-4mMw6:-MtDlHTPBQJVSH-4mMw7:b-3rgpsb) ([raw file](https://github.com/pmem/miniasync/blob/1c48587e8f60014570ec7c6b61319bf1cd3d5848/src/vdm.c#L64)):*
> ```C
> 	if (data->notifier.notifier_used == FUTURE_NOTIFIER_WAKER)
> 		FUTURE_WAKER_WAKE(&data->notifier.waker);
> 	util_atomic_store64(&data->complete, 1);
> ```

add a comment stating why this is after the waker.
___
*[src/vdm.c, line 170 at r6](https://reviewable.io/reviews/pmem/miniasync/33#-MtDlqYL0JArJ1ZjYPRu:-MtDlqYL0JArJ1ZjYPRv:b-9w3c4j) ([raw file](https://github.com/pmem/miniasync/blob/1c48587e8f60014570ec7c6b61319bf1cd3d5848/src/vdm.c#L170)):*
> ```C
> 
> void *
> vdm_threads_loop(void *arg)
> ```

this probably should also be moved?
___
*[src/vdm.c, line 184 at r6](https://reviewable.io/reviews/pmem/miniasync/33#-MtDm6FT2gsBttc8drG4:-MtDm6FT2gsBttc8drG5:batb9wf) ([raw file](https://github.com/pmem/miniasync/blob/1c48587e8f60014570ec7c6b61319bf1cd3d5848/src/vdm.c#L184)):*
> ```C
> 		data = ringbuf_dequeue(buf);
> 
> 		if (!vdm_threads_data->running)
> ```

just check for NULL return from dequeue.



_Code quote:_
```C
ringbuf_dequeue
```
___
*[src/vdm_threads.c, line 12 at r6](https://reviewable.io/reviews/pmem/miniasync/33#-MtDmQv7CxQvux0Qh6GK:-MtDmQv7CxQvux0Qh6GL:b9rr89o) ([raw file](https://github.com/pmem/miniasync/blob/1c48587e8f60014570ec7c6b61319bf1cd3d5848/src/vdm_threads.c#L12)):*
> ```C
> 
> #define THREADS_COUNT 12
> #define RINGBUF_SIZE 4
> ```

make it larger, like 128 or something
___
*[src/include/libminiasync/vdm.h, line 77 at r6](https://reviewable.io/reviews/pmem/miniasync/33#-MtDmiPW4bsjZ1asAyzC:-MtDmiPW4bsjZ1asAyzD:b-kz5gsq) ([raw file](https://github.com/pmem/miniasync/blob/1c48587e8f60014570ec7c6b61319bf1cd3d5848/src/include/libminiasync/vdm.h#L77)):*
> ```objc
> struct vdm_descriptor *vdm_descriptor_threads_polled(void);
> 
> void *vdm_threads_loop(void *arg);
> ```

move this to vdm_threads.h
___
*[src/include/libminiasync/vdm_threads.h, line 14 at r6](https://reviewable.io/reviews/pmem/miniasync/33#-MtDmn-uDPLI4HnoKpMj:-MtDmn-uDPLI4HnoKpMk:b-n9ae8c) ([raw file](https://github.com/pmem/miniasync/blob/1c48587e8f60014570ec7c6b61319bf1cd3d5848/src/include/libminiasync/vdm_threads.h#L14)):*
> ```objc
> #endif
> 
> struct vdm_threads_data {
> ```

does this need to be public?


<!-- Sent from Reviewable.io -->

2022-01-12 15:53 UTC, blazej-smorawski reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/miniasync/33)* status: 35 of 37 files reviewed, 11 unresolved discussions (waiting on @blazej-smorawski and @pbalcer)

___
*[doc/miniasync_vdm.3.md.in, line 65 at r3](https://reviewable.io/reviews/pmem/miniasync/33#-Mt3BCSZ81ISSqp_Prlv:-MtDuQVM1VG8c_-2OgU3:bw5xlq4) ([raw file](https://github.com/pmem/miniasync/blob/a1c0158cc17e30110f7edcc98c4d86b117a7d636/doc/miniasync_vdm.3.md.in#L65)):*
<details><summary><i>Previously, pbalcer (Piotr Balcer) wrote…</i></summary><blockquote>

you made typos ;)
`the queue is dequeued` looks odd.
</blockquote></details>

I hope there are no more typos :)
___
*[examples/basic-async/basic-async.c, line 9 at r3](https://reviewable.io/reviews/pmem/miniasync/33#-Mt3DdIj5JPGow38nhwd:-MtDuU_a1OVZi6k8rQox:b-b1ybvh) ([raw file](https://github.com/pmem/miniasync/blob/a1c0158cc17e30110f7edcc98c4d86b117a7d636/examples/basic-async/basic-async.c#L9)):*
<details><summary><i>Previously, pbalcer (Piotr Balcer) wrote…</i></summary><blockquote>

no?

int
main(void)
{
}
</blockquote></details>

It was a bad idea to write "done" when I was "planning" to do that. Now it's done.
___
*[src/vdm.c, line 184 at r6](https://reviewable.io/reviews/pmem/miniasync/33#-MtDm6FT2gsBttc8drG4:-MtDyrud-fjE1AzdwlmO:b-ovwawk) ([raw file](https://github.com/pmem/miniasync/blob/1c48587e8f60014570ec7c6b61319bf1cd3d5848/src/vdm.c#L184)):*
<details><summary><i>Previously, pbalcer (Piotr Balcer) wrote…</i></summary><blockquote>

just check for NULL return from dequeue.
</blockquote></details>

Good idea!
___
*[src/vdm_threads.c, line 12 at r6](https://reviewable.io/reviews/pmem/miniasync/33#-MtDmQv7CxQvux0Qh6GK:-MtDxOjQ2YVSO13JP9St:b-896fix) ([raw file](https://github.com/pmem/miniasync/blob/1c48587e8f60014570ec7c6b61319bf1cd3d5848/src/vdm_threads.c#L12)):*
<details><summary><i>Previously, pbalcer (Piotr Balcer) wrote…</i></summary><blockquote>

make it larger, like 128 or something
</blockquote></details>

Done.
___
*[src/include/libminiasync/vdm.h, line 77 at r6](https://reviewable.io/reviews/pmem/miniasync/33#-MtDmiPW4bsjZ1asAyzC:-MtDywSa-5tXodGvUSUl:boa6ei0) ([raw file](https://github.com/pmem/miniasync/blob/1c48587e8f60014570ec7c6b61319bf1cd3d5848/src/include/libminiasync/vdm.h#L77)):*
<details><summary><i>Previously, pbalcer (Piotr Balcer) wrote…</i></summary><blockquote>

move this to vdm_threads.h
</blockquote></details>

The problem is that this function has to know `memcpy_impl`, and at the same time it needs to know `vdm_threads_data`, so it can dequeue from ringbuf.


<!-- Sent from Reviewable.io -->

2022-01-13 07:16 UTC, blazej-smorawski reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/miniasync/33)* status: 30 of 37 files reviewed, 11 unresolved discussions (waiting on @pbalcer)

___
*[src/vdm.c, line 7 at r6](https://reviewable.io/reviews/pmem/miniasync/33#-MtDlg7vCCPtj1SIrJsA:-MtHFXR43PB3Syhm0aXv:bk56jji) ([raw file](https://github.com/pmem/miniasync/blob/1c48587e8f60014570ec7c6b61319bf1cd3d5848/src/vdm.c#L7)):*
<details><summary><i>Previously, pbalcer (Piotr Balcer) wrote…</i></summary><blockquote>

just move the entire descriptor out of this file. This shouldn't have to pull in this header.
</blockquote></details>

Done in a new draft.
___
*[src/vdm.c, line 32 at r6](https://reviewable.io/reviews/pmem/miniasync/33#-MtDkzEz6lMUjZJoK8rv:-MtH63CZBwfl2rkAsVWB:b-896fix) ([raw file](https://github.com/pmem/miniasync/blob/1c48587e8f60014570ec7c6b61319bf1cd3d5848/src/vdm.c#L32)):*
<details><summary><i>Previously, pbalcer (Piotr Balcer) wrote…</i></summary><blockquote>

why?
If you want to make the `vdm_data_init` fallible just change the function type to something that returns an int and check if the ret value is 0 (so `if (vdm_data_init(...) != 0) err;`) 
</blockquote></details>

Done.
___
*[src/vdm.c, line 64 at r6](https://reviewable.io/reviews/pmem/miniasync/33#-MtDlHTPBQJVSH-4mMw6:-MtH8VRZ95_oEBfiShW5:b-896fix) ([raw file](https://github.com/pmem/miniasync/blob/1c48587e8f60014570ec7c6b61319bf1cd3d5848/src/vdm.c#L64)):*
<details><summary><i>Previously, pbalcer (Piotr Balcer) wrote…</i></summary><blockquote>

add a comment stating why this is after the waker.
</blockquote></details>

Done.
___
*[src/vdm.c, line 170 at r6](https://reviewable.io/reviews/pmem/miniasync/33#-MtDlqYL0JArJ1ZjYPRu:-MtHFcGn9tE0II1CnrBE:b9w73ry) ([raw file](https://github.com/pmem/miniasync/blob/1c48587e8f60014570ec7c6b61319bf1cd3d5848/src/vdm.c#L170)):*
<details><summary><i>Previously, pbalcer (Piotr Balcer) wrote…</i></summary><blockquote>

this probably should also be moved?
</blockquote></details>

Done in the new draft.
___
*[src/include/libminiasync/vdm.h, line 77 at r6](https://reviewable.io/reviews/pmem/miniasync/33#-MtDmiPW4bsjZ1asAyzC:-MtHFpfa1J3iFBBvr0Mz:b-e717ud) ([raw file](https://github.com/pmem/miniasync/blob/1c48587e8f60014570ec7c6b61319bf1cd3d5848/src/include/libminiasync/vdm.h#L77)):*
<details><summary><i>Previously, blazej-smorawski wrote…</i></summary><blockquote>

The problem is that this function has to know `memcpy_impl`, and at the same time it needs to know `vdm_threads_data`, so it can dequeue from ringbuf.
</blockquote></details>

I moved it but at some cost - added the field `memcpy_impl` into `vdm_memcpy_data` and had to make `vdm_check` functions non-static and put them in vdm.h, so other implementations can use them. Couldn't figure any better way to do it.
___
*[src/include/libminiasync/vdm_threads.h, line 14 at r6](https://reviewable.io/reviews/pmem/miniasync/33#-MtDmn-uDPLI4HnoKpMj:-MtHFkiiE11PauG2wPhZ:bwi457j) ([raw file](https://github.com/pmem/miniasync/blob/1c48587e8f60014570ec7c6b61319bf1cd3d5848/src/include/libminiasync/vdm_threads.h#L14)):*
<details><summary><i>Previously, pbalcer (Piotr Balcer) wrote…</i></summary><blockquote>

does this need to be public?
</blockquote></details>

Not anymore.


<!-- Sent from Reviewable.io -->

2022-01-13 10:54 UTC, pbalcer requested changes
> Reviewed 1 of 12 files at r5, 1 of 6 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/miniasync/33)* status: 32 of 37 files reviewed, 6 unresolved discussions (waiting on @blazej-smorawski and @pbalcer)

___
*[doc/miniasync_vdm.3.md.in, line 65 at r3](https://reviewable.io/reviews/pmem/miniasync/33#-Mt3BCSZ81ISSqp_Prlv:-MtHx0ti6lNao9NJX-gn:b-7qgc4p) ([raw file](https://github.com/pmem/miniasync/blob/a1c0158cc17e30110f7edcc98c4d86b117a7d636/doc/miniasync_vdm.3.md.in#L65)):*
<details><summary><i>Previously, blazej-smorawski wrote…</i></summary><blockquote>

I hope there are no more typos :)
</blockquote></details>

'... tires to add its memcpy into the queue'

What queue? Put yourself in the shoes of a person reading this for the first time.
___
*[doc/miniasync_vdm.3.md.in, line 63 at r7](https://reviewable.io/reviews/pmem/miniasync/33#-MtHwouu3uM82V3lGnJu:-MtHwouv5_4xbo_Tr1Tx:b8jv4sz) ([raw file](https://github.com/pmem/miniasync/blob/0f9f2e1eb60d7baac1706c1a172ee99984148cc6/doc/miniasync_vdm.3.md.in#L63)):*
> ```
> From now on, every future created with `vdm_memcpy` and previously
> created instance of data mover `struct vdm_memcpy_future fut = vdm_memcpy(vdm, dst, src, size, flags);`
> will be performed asynchronously.
> ```

`every future ... and previously created instance ... will be performed asynchronously.`

That's not a correct sentence.
___
*[src/vdm.c, line 153 at r7](https://reviewable.io/reviews/pmem/miniasync/33#-MtI1dJx5E-qGAGKvOfL:-MtI1dJx5E-qGAGKvOfM:b-ssboth) ([raw file](https://github.com/pmem/miniasync/blob/0f9f2e1eb60d7baac1706c1a172ee99984148cc6/src/vdm.c#L153)):*
> ```C
> 	notifier->notifier_used = FUTURE_NOTIFIER_NONE;
> 
> 	memcpy_impl(descriptor, context);
> ```

change this to
```
memcpy(...);
complete = 1;
```
and move the memcpy_impl to the threads implementation. This will allow you to remove it from the header.
___
*[src/vdm_threads.c, line 25 at r7](https://reviewable.io/reviews/pmem/miniasync/33#-MtI2Z0t803Be6juT1LW:-MtI2Z0t803Be6juT1LX:bfxbw0k) ([raw file](https://github.com/pmem/miniasync/blob/0f9f2e1eb60d7baac1706c1a172ee99984148cc6/src/vdm_threads.c#L25)):*
> ```C
> 	struct vdm_threads_data *vdm_threads_data =
> 		malloc(sizeof(struct vdm_threads_data));
> ```

don't leave an empty line before an error check. it looks odd.
___
*[src/vdm_threads.c, line 26 at r7](https://reviewable.io/reviews/pmem/miniasync/33#-MtI26yl2qQj_AOTcMUs:-MtI26yl2qQj_AOTcMUt:b-7e0afo) ([raw file](https://github.com/pmem/miniasync/blob/0f9f2e1eb60d7baac1706c1a172ee99984148cc6/src/vdm_threads.c#L26)):*
> ```C
> 		malloc(sizeof(struct vdm_threads_data));
> 
> 	if (!vdm_threads_data) {
> ```

nit, but I don't like implict null-checks like that - I prefer it when NULL comparison is explicit `if (vdm_threads_data == NULL) return ...`. My personal preference is to only ever use booleans inside of implicit ifs.
___
*[src/vdm_threads.c, line 48 at r7](https://reviewable.io/reviews/pmem/miniasync/33#-MtI2m7c9HhxbbFmZlHI:-MtI2m7c9HhxbbFmZlHJ:b-vqxwld) ([raw file](https://github.com/pmem/miniasync/blob/0f9f2e1eb60d7baac1706c1a172ee99984148cc6/src/vdm_threads.c#L48)):*
> ```C
> 		vdm_threads_data->threads[i] = malloc(sizeof(os_thread_t));
> 
> 		if (!vdm_threads_data->threads[i]) {
> ```

read up on goto error handling idiom and apply it here.
___
*[src/include/libminiasync/vdm.h, line 77 at r6](https://reviewable.io/reviews/pmem/miniasync/33#-MtDmiPW4bsjZ1asAyzC:-MtI3aAmBuGiri18cjnk:b-6j8x1f) ([raw file](https://github.com/pmem/miniasync/blob/1c48587e8f60014570ec7c6b61319bf1cd3d5848/src/include/libminiasync/vdm.h#L77)):*
<details><summary><i>Previously, blazej-smorawski wrote…</i></summary><blockquote>

I moved it but at some cost - added the field `memcpy_impl` into `vdm_memcpy_data` and had to make `vdm_check` functions non-static and put them in vdm.h, so other implementations can use them. Couldn't figure any better way to do it.
</blockquote></details>

Just move the memcpy_impl into the threads implementation.


<!-- Sent from Reviewable.io -->

2022-01-14 07:54 UTC, blazej-smorawski reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/miniasync/33)* status: 31 of 37 files reviewed, 5 unresolved discussions (waiting on @pbalcer)

___
*[doc/miniasync_vdm.3.md.in, line 65 at r3](https://reviewable.io/reviews/pmem/miniasync/33#-Mt3BCSZ81ISSqp_Prlv:-MtMPOVG-rozlqzrGO5S:b-p9mpe8) ([raw file](https://github.com/pmem/miniasync/blob/a1c0158cc17e30110f7edcc98c4d86b117a7d636/doc/miniasync_vdm.3.md.in#L65)):*
<details><summary><i>Previously, pbalcer (Piotr Balcer) wrote…</i></summary><blockquote>

'... tires to add its memcpy into the queue'

What queue? Put yourself in the shoes of a person reading this for the first time.
</blockquote></details>

Tried to rewrite the whole thing, so it should be much easier to understand now. I hope I didn't go too much into detail, because I'm not sure how much knowledge the user will need. I wrote a little about future states which may be a little too deep, but I wanted to explain when a user can expect his future to be processed.
___
*[doc/miniasync_vdm.3.md.in, line 63 at r7](https://reviewable.io/reviews/pmem/miniasync/33#-MtHwouu3uM82V3lGnJu:-MtMPMCC4JNBh3vj__fS:b32n8ta) ([raw file](https://github.com/pmem/miniasync/blob/0f9f2e1eb60d7baac1706c1a172ee99984148cc6/doc/miniasync_vdm.3.md.in#L63)):*
<details><summary><i>Previously, pbalcer (Piotr Balcer) wrote…</i></summary><blockquote>

`every future ... and previously created instance ... will be performed asynchronously.`

That's not a correct sentence.
</blockquote></details>

Removed it.
___
*[src/vdm.c, line 153 at r7](https://reviewable.io/reviews/pmem/miniasync/33#-MtI1dJx5E-qGAGKvOfL:-MtMTcnw20zcVWx0sDal:b-896fix) ([raw file](https://github.com/pmem/miniasync/blob/0f9f2e1eb60d7baac1706c1a172ee99984148cc6/src/vdm.c#L153)):*
<details><summary><i>Previously, pbalcer (Piotr Balcer) wrote…</i></summary><blockquote>

change this to
```
memcpy(...);
complete = 1;
```
and move the memcpy_impl to the threads implementation. This will allow you to remove it from the header.
</blockquote></details>

Done.
___
*[src/vdm_threads.c, line 25 at r7](https://reviewable.io/reviews/pmem/miniasync/33#-MtI2Z0t803Be6juT1LW:-MtMU5CE0-8HdsRQ2Ltx:b-896fix) ([raw file](https://github.com/pmem/miniasync/blob/0f9f2e1eb60d7baac1706c1a172ee99984148cc6/src/vdm_threads.c#L25)):*
<details><summary><i>Previously, pbalcer (Piotr Balcer) wrote…</i></summary><blockquote>

don't leave an empty line before an error check. it looks odd.
</blockquote></details>

Done.
___
*[src/vdm_threads.c, line 26 at r7](https://reviewable.io/reviews/pmem/miniasync/33#-MtI26yl2qQj_AOTcMUs:-MtMUQfX-3LDg4pTtLjK:bkr465f) ([raw file](https://github.com/pmem/miniasync/blob/0f9f2e1eb60d7baac1706c1a172ee99984148cc6/src/vdm_threads.c#L26)):*
<details><summary><i>Previously, pbalcer (Piotr Balcer) wrote…</i></summary><blockquote>

nit, but I don't like implict null-checks like that - I prefer it when NULL comparison is explicit `if (vdm_threads_data == NULL) return ...`. My personal preference is to only ever use booleans inside of implicit ifs.
</blockquote></details>

Sure, I get it. Explicit one will be easier to understand.
___
*[src/vdm_threads.c, line 48 at r7](https://reviewable.io/reviews/pmem/miniasync/33#-MtI2m7c9HhxbbFmZlHI:-MtMXDlyAvunHjm4IaQv:b-896fix) ([raw file](https://github.com/pmem/miniasync/blob/0f9f2e1eb60d7baac1706c1a172ee99984148cc6/src/vdm_threads.c#L48)):*
<details><summary><i>Previously, pbalcer (Piotr Balcer) wrote…</i></summary><blockquote>

read up on goto error handling idiom and apply it here.
</blockquote></details>

Done.
___
*[src/include/libminiasync/vdm.h, line 77 at r6](https://reviewable.io/reviews/pmem/miniasync/33#-MtDmiPW4bsjZ1asAyzC:-MtMXGcJ93hNtYltKSDC:b-896fix) ([raw file](https://github.com/pmem/miniasync/blob/1c48587e8f60014570ec7c6b61319bf1cd3d5848/src/include/libminiasync/vdm.h#L77)):*
<details><summary><i>Previously, pbalcer (Piotr Balcer) wrote…</i></summary><blockquote>

Just move the memcpy_impl into the threads implementation.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-01-14 14:02 UTC, pbalcer requested changes
looks OK, just a few minor nits...

> Reviewed 3 of 6 files at r8, 3 of 3 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/miniasync/33#-:-MtNtNAl9eyrp4PGSeRO:bslikr3)* status: all files reviewed, 8 unresolved discussions (waiting on @blazej-smorawski)

___
*[doc/miniasync_vdm.3.md.in, line 68 at r9](https://reviewable.io/reviews/pmem/miniasync/33#-MtNsBIQ4Q2mbT-ype9q:-MtNsBIQ4Q2mbT-ype9r:bg7dk5a) ([raw file](https://github.com/pmem/miniasync/blob/fae971757693b1b6b35cdca2907c555aff5e050c/doc/miniasync_vdm.3.md.in#L68)):*
> ```
> as long as it is not complete i.e. its state is not `FUTURE_STATE_COMPLETE`. 
> When this kind of future is polled and it is in state `FUTURE_STATE_IDLE`, 
> it tries to add its memcpy data into a buffer 
> ```

'into a list of pending operations'
'into a queue of pending operations'
___
*[doc/miniasync_vdm.3.md.in, line 69 at r9](https://reviewable.io/reviews/pmem/miniasync/33#-MtNqe7NDVyhWUmbfUm_:-MtNqe7NDVyhWUmbfUma:b2nif2c) ([raw file](https://github.com/pmem/miniasync/blob/fae971757693b1b6b35cdca2907c555aff5e050c/doc/miniasync_vdm.3.md.in#L69)):*
> ```
> When this kind of future is polled and it is in state `FUTURE_STATE_IDLE`, 
> it tries to add its memcpy data into a buffer 
> that is watched by worker threads. If the memcpy data were added to the buffer
> ```

was
___
*[doc/miniasync_vdm.3.md.in, line 70 at r9](https://reviewable.io/reviews/pmem/miniasync/33#-MtNqnq_31V75aaGdNbu:-MtNqnq_31V75aaGdNbv:b-4v5lol) ([raw file](https://github.com/pmem/miniasync/blob/fae971757693b1b6b35cdca2907c555aff5e050c/doc/miniasync_vdm.3.md.in#L70)):*
> ```
> it tries to add its memcpy data into a buffer 
> that is watched by worker threads. If the memcpy data were added to the buffer
> successfully, the state of the future is set to `FUTURE_STATE_RUNNING`, because
> ```

which guarantees that a worker thread will perform this operation.
___
*[doc/miniasync_vdm.3.md.in, line 72 at r9](https://reviewable.io/reviews/pmem/miniasync/33#-MtNqt5y1EsPW0bIbhCZ:-MtNqt5y1EsPW0bIbhC_:b6hhk61) ([raw file](https://github.com/pmem/miniasync/blob/fae971757693b1b6b35cdca2907c555aff5e050c/doc/miniasync_vdm.3.md.in#L72)):*
> ```
> successfully, the state of the future is set to `FUTURE_STATE_RUNNING`, because
> we have a guarantee that some worker thread will perform this memcpy. Otherwise,
> the state is set to `FUTURE_STATE_IDLE` and whole process is repeated again in a
> ```

just "repeated".
"repeated again" is a pleonasm ('again' is redundant)
___
*[doc/miniasync_vdm.3.md.in, line 76 at r9](https://reviewable.io/reviews/pmem/miniasync/33#-MtNrsbF9gBrukeq-_dc:-MtNrsbF9gBrukeq-_dd:bqaayjz) ([raw file](https://github.com/pmem/miniasync/blob/fae971757693b1b6b35cdca2907c555aff5e050c/doc/miniasync_vdm.3.md.in#L76)):*
> ```
> a check if it's complete, so if it is - its state is set to `FUTURE_STATE_COMPLETE`,
> otherwise it is still `FUTURE_STATE_RUNNING`. Worker threads perform memcpy
> operations based on the data they receive from the buffer regarding FIFO policy.
> ```

that last sentence doesn't work.

Just say that the operations are processed in the order in which they are stored in the queue/list/buffer.
___
*[src/vdm.c, line 10 at r9](https://reviewable.io/reviews/pmem/miniasync/33#-MtNsWHv0Tc_XdBGQYYJ:-MtNsWHv0Tc_XdBGQYYK:bofvzgd) ([raw file](https://github.com/pmem/miniasync/blob/fae971757693b1b6b35cdca2907c555aff5e050c/src/vdm.c#L10)):*
> ```C
> 
> struct vdm {
>     struct vdm_descriptor *descriptor;
> ```

tabs (just run cstyle)
___
*[src/vdm.c, line 22 at r9](https://reviewable.io/reviews/pmem/miniasync/33#-MtNshOt-6_OoMEHi4TU:-MtNshOt-6_OoMEHi4TV:bkkwu5d) ([raw file](https://github.com/pmem/miniasync/blob/fae971757693b1b6b35cdca2907c555aff5e050c/src/vdm.c#L22)):*
> ```C
> {
> 	struct vdm *vdm = malloc(sizeof(struct vdm));
> ```

remove the empty line.
___
*[src/vdm.c, line 23 at r9](https://reviewable.io/reviews/pmem/miniasync/33#-MtNsfI61O6lHYFiATkk:-MtNsfI61O6lHYFiATkl:b-6axoe7) ([raw file](https://github.com/pmem/miniasync/blob/fae971757693b1b6b35cdca2907c555aff5e050c/src/vdm.c#L23)):*
> ```C
> 	struct vdm *vdm = malloc(sizeof(struct vdm));
> 
> 	if (!vdm)
> ```

vdm == NULL


<!-- Sent from Reviewable.io -->

2022-01-17 07:30 UTC, blazej-smorawski reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/miniasync/33)* status: 33 of 37 files reviewed, 8 unresolved discussions (waiting on @pbalcer)

___
*[doc/miniasync_vdm.3.md.in, line 68 at r9](https://reviewable.io/reviews/pmem/miniasync/33#-MtNsBIQ4Q2mbT-ype9q:-Mtah9fj59tqe2i5ji7U:b-896fix) ([raw file](https://github.com/pmem/miniasync/blob/fae971757693b1b6b35cdca2907c555aff5e050c/doc/miniasync_vdm.3.md.in#L68)):*
<details><summary><i>Previously, pbalcer (Piotr Balcer) wrote…</i></summary><blockquote>

'into a list of pending operations'
'into a queue of pending operations'

</blockquote></details>

Done.
___
*[doc/miniasync_vdm.3.md.in, line 69 at r9](https://reviewable.io/reviews/pmem/miniasync/33#-MtNqe7NDVyhWUmbfUm_:-MtahKee5K3D1eNIhVWp:b-896fix) ([raw file](https://github.com/pmem/miniasync/blob/fae971757693b1b6b35cdca2907c555aff5e050c/doc/miniasync_vdm.3.md.in#L69)):*
<details><summary><i>Previously, pbalcer (Piotr Balcer) wrote…</i></summary><blockquote>

was
</blockquote></details>

Done.
___
*[doc/miniasync_vdm.3.md.in, line 70 at r9](https://reviewable.io/reviews/pmem/miniasync/33#-MtNqnq_31V75aaGdNbu:-MtahYEP-mfJhNJcgVZi:b-896fix) ([raw file](https://github.com/pmem/miniasync/blob/fae971757693b1b6b35cdca2907c555aff5e050c/doc/miniasync_vdm.3.md.in#L70)):*
<details><summary><i>Previously, pbalcer (Piotr Balcer) wrote…</i></summary><blockquote>

which guarantees that a worker thread will perform this operation.
</blockquote></details>

Done.
___
*[doc/miniasync_vdm.3.md.in, line 72 at r9](https://reviewable.io/reviews/pmem/miniasync/33#-MtNqt5y1EsPW0bIbhCZ:-Mtai5oq36GcjowStJ6a:b-896fix) ([raw file](https://github.com/pmem/miniasync/blob/fae971757693b1b6b35cdca2907c555aff5e050c/doc/miniasync_vdm.3.md.in#L72)):*
<details><summary><i>Previously, pbalcer (Piotr Balcer) wrote…</i></summary><blockquote>

just "repeated".
"repeated again" is a pleonasm ('again' is redundant)
</blockquote></details>

Done.
___
*[doc/miniasync_vdm.3.md.in, line 76 at r9](https://reviewable.io/reviews/pmem/miniasync/33#-MtNrsbF9gBrukeq-_dc:-Mtal-AM92xMDfl6Fu94:b-896fix) ([raw file](https://github.com/pmem/miniasync/blob/fae971757693b1b6b35cdca2907c555aff5e050c/doc/miniasync_vdm.3.md.in#L76)):*
<details><summary><i>Previously, pbalcer (Piotr Balcer) wrote…</i></summary><blockquote>

that last sentence doesn't work.

Just say that the operations are processed in the order in which they are stored in the queue/list/buffer.
</blockquote></details>

Done.
___
*[src/vdm.c, line 10 at r9](https://reviewable.io/reviews/pmem/miniasync/33#-MtNsWHv0Tc_XdBGQYYJ:-MtalaR4DmH_FyjwqsUZ:b-896fix) ([raw file](https://github.com/pmem/miniasync/blob/fae971757693b1b6b35cdca2907c555aff5e050c/src/vdm.c#L10)):*
<details><summary><i>Previously, pbalcer (Piotr Balcer) wrote…</i></summary><blockquote>

tabs (just run cstyle)
</blockquote></details>

Done.
___
*[src/vdm.c, line 22 at r9](https://reviewable.io/reviews/pmem/miniasync/33#-MtNshOt-6_OoMEHi4TU:-Mtal_Zz0QvrPjHGVlYR:b-896fix) ([raw file](https://github.com/pmem/miniasync/blob/fae971757693b1b6b35cdca2907c555aff5e050c/src/vdm.c#L22)):*
<details><summary><i>Previously, pbalcer (Piotr Balcer) wrote…</i></summary><blockquote>

remove the empty line.
</blockquote></details>

Done.
___
*[src/vdm.c, line 23 at r9](https://reviewable.io/reviews/pmem/miniasync/33#-MtNsfI61O6lHYFiATkk:-Mtal_p2Av1o-vpwz75D:b-896fix) ([raw file](https://github.com/pmem/miniasync/blob/fae971757693b1b6b35cdca2907c555aff5e050c/src/vdm.c#L23)):*
<details><summary><i>Previously, pbalcer (Piotr Balcer) wrote…</i></summary><blockquote>

vdm == NULL
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-01-17 07:56 UTC, pbalcer approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 4 files at r10.
> *[Reviewable](https://reviewable.io/reviews/pmem/miniasync/33#-:-Mtb1LSb9nj-Dptx62WG:bnfp4nl)* status: 34 of 37 files reviewed, 1 unresolved discussion (waiting on @blazej-smorawski and @pbalcer)

___
*[src/vdm.c, line 73 at r10](https://reviewable.io/reviews/pmem/miniasync/33#-Mtb1Fuv3ibjKF9cHkGo:-Mtb1Fuv3ibjKF9cHkGp:b3i89x6) ([raw file](https://github.com/pmem/miniasync/blob/78ee4f109a311e10e2f13c0581d6d42f47dd1cbd/src/vdm.c#L73)):*
> ```C
> 	util_atomic_store32(&data->complete, 1);
> 	/*
> 	 * Just a dirty test of supressing helgrind errors
> ```

remove this for now.


<!-- Sent from Reviewable.io -->

2022-01-17 13:49 UTC, kswiecicki commented
___
*[examples/basic-async/basic-async.c, line 22 at r11](https://reviewable.io/reviews/pmem/miniasync/33#-MtcHv_t4RjEFn_LekNf:-MtcHv_u7IIY6xCp4SBx:b-eyq6fz) ([raw file](https://github.com/pmem/miniasync/blob/2170207a20858a9881f2b67f12f513453a6133ab/examples/basic-async/basic-async.c#L22)):*
> ```C
> 		char *dst1 = malloc(test_size * sizeof(char));
> 		char *src2 = malloc(test_size * 2 * sizeof(char));
> 		char *dst2 = malloc(test_size * 2 * sizeof(char));
> ```

This could be moved out of loop.



_Code quote:_
```C
		char *src1 = malloc(test_size * sizeof(char));
		char *dst1 = malloc(test_size * sizeof(char));
		char *src2 = malloc(test_size * 2 * sizeof(char));
		char *dst2 = malloc(test_size * 2 * sizeof(char));
```


<!-- Sent from Reviewable.io -->

2022-01-18 07:27 UTC, blazej-smorawski reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/miniasync/33)* status: 33 of 37 files reviewed, 2 unresolved discussions (waiting on @kswiecicki and @pbalcer)

___
*[examples/basic-async/basic-async.c, line 22 at r11](https://reviewable.io/reviews/pmem/miniasync/33#-MtcHv_t4RjEFn_LekNf:-Mtg2lWI6zVywMIa7lBq:bfae8h) ([raw file](https://github.com/pmem/miniasync/blob/2170207a20858a9881f2b67f12f513453a6133ab/examples/basic-async/basic-async.c#L22)):*
<details><summary><i>Previously, kswiecicki (Krzysztof Święcicki) wrote…</i></summary><blockquote>

This could be moved out of loop.
</blockquote></details>

Sure, but my idea was to show that we can perform various unique operations on one runner and one set of threads, so I wanted to have unique addresses from malloc.
___
*[src/vdm.c, line 73 at r10](https://reviewable.io/reviews/pmem/miniasync/33#-Mtb1Fuv3ibjKF9cHkGo:-MtbdSVW3s1Tfx2BuA9T:b-896fix) ([raw file](https://github.com/pmem/miniasync/blob/78ee4f109a311e10e2f13c0581d6d42f47dd1cbd/src/vdm.c#L73)):*
<details><summary><i>Previously, pbalcer (Piotr Balcer) wrote…</i></summary><blockquote>

remove this for now.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-01-18 08:03 UTC, DamianDuy commented on doc/miniasync_vdm.3.md.in
> +it tries to add its memcpy data into a into a queue of pending operations
There's double ```into a``` mistype.

2022-01-18 08:10 UTC, DamianDuy commented on src/core/ringbuf.c
> +/* Copyright 2017-2019, Intel Corporation */
2022

2022-01-18 08:52 UTC, blazej-smorawski reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/miniasync/33)* status: 33 of 37 files reviewed, 4 unresolved discussions (waiting on @DamianDuy, @kswiecicki, and @pbalcer)

___
*[doc/miniasync_vdm.3.md.in, line 68 at r11](https://reviewable.io/reviews/pmem/miniasync/33#-Mt1l1YRKi4JWkBWGFFR-r11-68:-MtgNJGnCSufimcls3hT:b-896fix) ([raw file](https://github.com/pmem/miniasync/blob/2170207a20858a9881f2b67f12f513453a6133ab/doc/miniasync_vdm.3.md.in#L68)):*
<details><summary><i>Previously, DamianDuy (Damian Duy) wrote…</i></summary><blockquote>

There's double  "```into a```" mistype.
</blockquote></details>

Done.
___
*[src/core/ringbuf.c, line 2 at r11](https://reviewable.io/reviews/pmem/miniasync/33#-MsEfSvFE6Zl5940pKzy-r11-2:-MtgNlvj-IB9_KddpXdh:b-896fix) ([raw file](https://github.com/pmem/miniasync/blob/2170207a20858a9881f2b67f12f513453a6133ab/src/core/ringbuf.c#L2)):*
<details><summary><i>Previously, DamianDuy (Damian Duy) wrote…</i></summary><blockquote>

2022
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-01-18 09:04 UTC, wlemkows requested changes

2022-01-18 09:04 UTC, wlemkows commented on doc/miniasync_vdm.3.md.in
> +`struct vdm_descriptor *vdm_descriptor_threads(void);`
It looks only vmd_new/deleve will stay in here. Please update SYNOPSIS and add adequate description and references to you new man page (@kswiecicki - same situation)

2022-01-18 09:04 UTC, wlemkows commented on doc/miniasync_vdm.3.md.in
> +:   In order to use parallel memcpy on os threads, create an appropriate
os threads -> do not use shortcuts

2022-01-18 09:04 UTC, wlemkows commented on examples/basic-async/basic-async.c
> +/* Copyright 2021, Intel Corporation */
Why does it works? 22

2022-01-18 09:04 UTC, wlemkows commented on src/core/ringbuf.c
> +/* Copyright 2017-2021, Intel Corporation */
.

2022-01-18 09:07 UTC, wlemkows commented on examples/basic-async/basic-async.c
> +main(void)
Example for the user should be documented (README) or commented properly in the code.

2022-01-19 14:31 UTC, blazej-smorawski reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/miniasync/33)* status: 30 of 37 files reviewed, 7 unresolved discussions (waiting on @kswiecicki, @pbalcer, and @wlemkows)

___
*[doc/miniasync_vdm.3.md.in, line 50 at r12](https://reviewable.io/reviews/pmem/miniasync/33#-Mt1l1YRKi4JWkBWGFFR-r12-50:-MtmeVmD0qSaMbnZnCpI:b-896fix) ([raw file](https://github.com/pmem/miniasync/blob/1d85b834cfc7db7d77451088cca9f94974055d23/doc/miniasync_vdm.3.md.in#L50)):*
<details><summary><i>Previously, wlemkows (Weronika Lewandowska) wrote…</i></summary><blockquote>

It looks only vmd_new/deleve will stay in here. Please update SYNOPSIS and add adequate description and references to you new man page (@kswiecicki - same situation)
</blockquote></details>

Done.
___
*[doc/miniasync_vdm.3.md.in, line 52 at r12](https://reviewable.io/reviews/pmem/miniasync/33#-Mt1l1YRKi4JWkBWGFFR-r12-52:-Mtmf9MS25AaDUJX8UuF:b-896fix) ([raw file](https://github.com/pmem/miniasync/blob/1d85b834cfc7db7d77451088cca9f94974055d23/doc/miniasync_vdm.3.md.in#L52)):*
<details><summary><i>Previously, wlemkows (Weronika Lewandowska) wrote…</i></summary><blockquote>

os threads -> do not use shortcuts
</blockquote></details>

Done.
___
*[examples/basic-async/basic-async.c, line 2 at r12](https://reviewable.io/reviews/pmem/miniasync/33#-MsEfSvFE6Zl5940pKzw-r12-2:-MtmfXtHAla3H70skrsI:b-896fix) ([raw file](https://github.com/pmem/miniasync/blob/1d85b834cfc7db7d77451088cca9f94974055d23/examples/basic-async/basic-async.c#L2)):*
<details><summary><i>Previously, wlemkows (Weronika Lewandowska) wrote…</i></summary><blockquote>

Why does it works? 22
</blockquote></details>

Done.
___
*[examples/basic-async/basic-async.c, line 9 at r12](https://reviewable.io/reviews/pmem/miniasync/33#-MsEfSvFE6Zl5940pKzw-r12-9:-MtmipoZ6igSgvuz_h06:b-896fix) ([raw file](https://github.com/pmem/miniasync/blob/1d85b834cfc7db7d77451088cca9f94974055d23/examples/basic-async/basic-async.c#L9)):*
<details><summary><i>Previously, wlemkows (Weronika Lewandowska) wrote…</i></summary><blockquote>

Example for the user should be documented (README) or commented properly in the code.
</blockquote></details>

Done.
___
*[src/core/ringbuf.c, line 2 at r12](https://reviewable.io/reviews/pmem/miniasync/33#-MsEfSvFE6Zl5940pKzy-r12-2:-Mtmjewx1tHtNURZrMET:b-896fix) ([raw file](https://github.com/pmem/miniasync/blob/1d85b834cfc7db7d77451088cca9f94974055d23/src/core/ringbuf.c#L2)):*
<details><summary><i>Previously, wlemkows (Weronika Lewandowska) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-01-24 11:25 UTC, wlemkows requested changes

2022-01-24 11:25 UTC, wlemkows commented on doc/miniasync_vdm_threads.3.md.in
> +**miniasync**(7), **miniasync_vdm**(3), **miniasync_future**(3), **miniasync_runtime**(3) and **<https://pmem.io>**
Use num order and then alphabetical order

2022-01-24 11:25 UTC, wlemkows commented on doc/miniasync_vdm_threads.3.md.in
> +XXX add description here.
Why you are not able to add this description?

2022-01-24 11:40 UTC, wlemkows requested changes
> Reviewed 4 of 9 files at r13.
> *[Reviewable](https://reviewable.io/reviews/pmem/miniasync/33)* status: 31 of 40 files reviewed, 10 unresolved discussions (waiting on @blazej-smorawski, @DamianDuy, @kswiecicki, @pbalcer, and @wlemkows)

___
*[doc/miniasync_vdm_synchronous.3.md.in, line 55 at r14](https://reviewable.io/reviews/pmem/miniasync/33#-MuAoVCYAOdC0Y6b-QcM:-MuAoVCZ0X5iVy-mda5Y:bjtf9rs) ([raw file](https://github.com/pmem/miniasync/blob/978022ebca2a946bfbd3972f162634f04c6f3374/doc/miniasync_vdm_synchronous.3.md.in#L55)):*
> ```
> the memcpy operation will be performed synchronously on the same thread as 
> `runtime_wait`.
> ## ERRORS ##
> ```

new line above, and fill this ERROR section or remove.
___
*[doc/miniasync_vdm_synchronous.3.md.in, line 62 at r14](https://reviewable.io/reviews/pmem/miniasync/33#-MuAoj1N65IOR2mH2D6T:-MuAoj1N65IOR2mH2D6U:b76meti) ([raw file](https://github.com/pmem/miniasync/blob/978022ebca2a946bfbd3972f162634f04c6f3374/doc/miniasync_vdm_synchronous.3.md.in#L62)):*
> ```
> # SEE ALSO #
> 
> **miniasync**(7), **miniasync_vdm**(3), **miniasync_future**(3), **miniasync_runtime**(3) and **<https://pmem.io>**
> ```

vmd_memcpy
vdm_new
___
*[examples/basic-async/basic-async.c, line 21 at r14](https://reviewable.io/reviews/pmem/miniasync/33#-MuAr9zO9D4kTESgrf-x:-MuAr9zTChWZYM6nkiaf:b-4fe0i7) ([raw file](https://github.com/pmem/miniasync/blob/978022ebca2a946bfbd3972f162634f04c6f3374/examples/basic-async/basic-async.c#L21)):*
> ```C
> 	struct vdm *vdm = vdm_new(vdm_async_descriptor);
> 
> 	size_t test_size = 1 << 10;
> ```

use define macro for this size
___
*[examples/basic-async/basic-async.c, line 38 at r14](https://reviewable.io/reviews/pmem/miniasync/33#-MuArc57B590lnVnlZBk:-MuArc57B590lnVnlZBl:b-d1h9xm) ([raw file](https://github.com/pmem/miniasync/blob/978022ebca2a946bfbd3972f162634f04c6f3374/examples/basic-async/basic-async.c#L38)):*
> ```C
> 
> 		/*
> 		 * Create futures to be performed asynchronously
> ```

. at the end
___
*[src/vdm.c, line 15 at r14](https://reviewable.io/reviews/pmem/miniasync/33#-MuAs5XT0aDpx9Wn5NSh:-MuAs5XV1R2B-iP7oUQ3:bo545or) ([raw file](https://github.com/pmem/miniasync/blob/978022ebca2a946bfbd3972f162634f04c6f3374/src/vdm.c#L15)):*
> ```C
> 
> /*
>  * Returns NULL if failed to allocate memory for struct vdm
> ```

add vdm_new -- at eh begining (look at other comments to function eg. in the pmdk repo)
___
*[src/vdm.c, line 19 at r14](https://reviewable.io/reviews/pmem/miniasync/33#-MuAsR9R9sSboRC8qR8c:-MuAsR9R9sSboRC8qR8d:b-7pkdwz) ([raw file](https://github.com/pmem/miniasync/blob/978022ebca2a946bfbd3972f162634f04c6f3374/src/vdm.c#L19)):*
> ```C
>  */
> struct vdm *
> vdm_new(struct vdm_descriptor *descriptor)
> ```

It would be nice to add description to vdm_new/delete to the man page.


<!-- Sent from Reviewable.io -->

2022-01-24 11:47 UTC, wlemkows requested changes
> Reviewed 1 of 3 files at r11.
> *[Reviewable](https://reviewable.io/reviews/pmem/miniasync/33)* status: 32 of 40 files reviewed, 11 unresolved discussions (waiting on @blazej-smorawski, @DamianDuy, @kswiecicki, @pbalcer, and @wlemkows)

___
*[src/vdm_threads.c, line 17 at r14](https://reviewable.io/reviews/pmem/miniasync/33#-MuAuFlPEoTvNmf7WAnT:-MuAuFlT4fQub6lOZVcC:bvlh84l) ([raw file](https://github.com/pmem/miniasync/blob/978022ebca2a946bfbd3972f162634f04c6f3374/src/vdm_threads.c#L17)):*
> ```C
> };
> 
> static void
> ```

ALL functions should have a comment above.


<!-- Sent from Reviewable.io -->

2022-01-24 12:11 UTC, wlemkows requested changes
> Reviewed 1 of 1 files at r14.
> *[Reviewable](https://reviewable.io/reviews/pmem/miniasync/33)* status: 33 of 40 files reviewed, 13 unresolved discussions (waiting on @blazej-smorawski, @DamianDuy, @kswiecicki, @pbalcer, and @wlemkows)

___
*[src/include/libminiasync/vdm.h, line 41 at r14](https://reviewable.io/reviews/pmem/miniasync/33#-MuAz_av1PMEBf6X2VXt:-MuAz_ayEY_mZH9zq02c:batv3ox) ([raw file](https://github.com/pmem/miniasync/blob/978022ebca2a946bfbd3972f162634f04c6f3374/src/include/libminiasync/vdm.h#L41)):*
> ```objc
> 	struct future_notifier notifier;
> 	int32_t started;
>     	int32_t complete;
> ```

wrong indentation
___
*[src/include/libminiasync/vdm_threads.h, line 4 at r14](https://reviewable.io/reviews/pmem/miniasync/33#-MuAzs6X8rN5Puuru7vU:-MuAzs6_E_Hdb-OhJjaf:bpa8l44) ([raw file](https://github.com/pmem/miniasync/blob/978022ebca2a946bfbd3972f162634f04c6f3374/src/include/libminiasync/vdm_threads.h#L4)):*
> ```objc
> /* Copyright 2022, Intel Corporation */
> 
> #ifndef VDM_THREAD_H
> ```

THREADS


<!-- Sent from Reviewable.io -->

2022-01-24 13:24 UTC, wlemkows requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/miniasync/33)* status: 33 of 40 files reviewed, 14 unresolved discussions (waiting on @blazej-smorawski, @DamianDuy, @kswiecicki, @pbalcer, and @wlemkows)

___
*[tests/memcpy_threads/test_memcpy_threads.cmake, line 4 at r14](https://reviewable.io/reviews/pmem/miniasync/33#-MuBENOk0iFP7wx7bPNt:-MuBENOm6MWd4Nr3ryI1:b-v4ufxz) ([raw file](https://github.com/pmem/miniasync/blob/978022ebca2a946bfbd3972f162634f04c6f3374/tests/memcpy_threads/test_memcpy_threads.cmake#L4)):*
> ```CMake
> # Copyright 2022, Intel Corporation
> 
> # test for the basic example
> ```

Is this test for basic example?? Do you have test for basic-async?


<!-- Sent from Reviewable.io -->

2022-01-24 13:55 UTC, wlemkows commented on src/vdm.c
> +	if (descriptor->vdm_data_init) {
null reference if user arg is null

2022-01-24 19:57 UTC, blazej-smorawski reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/miniasync/33)* status: 26 of 40 files reviewed, 14 unresolved discussions (waiting on @DamianDuy, @kswiecicki, @pbalcer, and @wlemkows)

___
*[doc/miniasync_vdm_synchronous.3.md.in, line 55 at r14](https://reviewable.io/reviews/pmem/miniasync/33#-MuAoVCYAOdC0Y6b-QcM:-MuCRgnN3cjdQ9aIa9_v:b-896fix) ([raw file](https://github.com/pmem/miniasync/blob/978022ebca2a946bfbd3972f162634f04c6f3374/doc/miniasync_vdm_synchronous.3.md.in#L55)):*
<details><summary><i>Previously, wlemkows (Weronika Lewandowska) wrote…</i></summary><blockquote>

new line above, and fill this ERROR section or remove.
</blockquote></details>

Done.
___
*[doc/miniasync_vdm_synchronous.3.md.in, line 62 at r14](https://reviewable.io/reviews/pmem/miniasync/33#-MuAoj1N65IOR2mH2D6T:-MuCV-Ez5AiVTzvxmRTA:b-896fix) ([raw file](https://github.com/pmem/miniasync/blob/978022ebca2a946bfbd3972f162634f04c6f3374/doc/miniasync_vdm_synchronous.3.md.in#L62)):*
<details><summary><i>Previously, wlemkows (Weronika Lewandowska) wrote…</i></summary><blockquote>

vmd_memcpy
vdm_new

</blockquote></details>

Done.
___
*[doc/miniasync_vdm_threads.3.md.in, line 70 at r14](https://reviewable.io/reviews/pmem/miniasync/33#-Mtmk6eyHIuohJAzm4H--r14-70:-MuCVSgZ5EJb-hH9jiJh:b-lid1ex) ([raw file](https://github.com/pmem/miniasync/blob/978022ebca2a946bfbd3972f162634f04c6f3374/doc/miniasync_vdm_threads.3.md.in#L70)):*
<details><summary><i>Previously, wlemkows (Weronika Lewandowska) wrote…</i></summary><blockquote>

Why you are not able to add this description?
</blockquote></details>

I did not have any knowledge of existing errors here, so I left it empty. I didn't remove this header because I thought that those manpages are still in a draft stage and will be rewritten in the nearest future.
___
*[doc/miniasync_vdm_threads.3.md.in, line 75 at r14](https://reviewable.io/reviews/pmem/miniasync/33#-Mtmk6eyHIuohJAzm4H--r14-75:-MuCWQfN2zTKYb3Ap_tW:b-896fix) ([raw file](https://github.com/pmem/miniasync/blob/978022ebca2a946bfbd3972f162634f04c6f3374/doc/miniasync_vdm_threads.3.md.in#L75)):*
<details><summary><i>Previously, wlemkows (Weronika Lewandowska) wrote…</i></summary><blockquote>

Use num order and then alphabetical order
</blockquote></details>

Done.
___
*[examples/basic-async/basic-async.c, line 21 at r14](https://reviewable.io/reviews/pmem/miniasync/33#-MuAr9zO9D4kTESgrf-x:-MuCWm7HBGHP75XN1FMD:b-896fix) ([raw file](https://github.com/pmem/miniasync/blob/978022ebca2a946bfbd3972f162634f04c6f3374/examples/basic-async/basic-async.c#L21)):*
<details><summary><i>Previously, wlemkows (Weronika Lewandowska) wrote…</i></summary><blockquote>

use define macro for this size
</blockquote></details>

Done.
___
*[examples/basic-async/basic-async.c, line 38 at r14](https://reviewable.io/reviews/pmem/miniasync/33#-MuArc57B590lnVnlZBk:-MuCWqrJ12Xm0Jf-vlXh:b-896fix) ([raw file](https://github.com/pmem/miniasync/blob/978022ebca2a946bfbd3972f162634f04c6f3374/examples/basic-async/basic-async.c#L38)):*
<details><summary><i>Previously, wlemkows (Weronika Lewandowska) wrote…</i></summary><blockquote>

. at the end
</blockquote></details>

Done.
___
*[src/vdm.c, line 15 at r14](https://reviewable.io/reviews/pmem/miniasync/33#-MuAs5XT0aDpx9Wn5NSh:-MuCXUhw7oFCIzVtzjWB:b-896fix) ([raw file](https://github.com/pmem/miniasync/blob/978022ebca2a946bfbd3972f162634f04c6f3374/src/vdm.c#L15)):*
<details><summary><i>Previously, wlemkows (Weronika Lewandowska) wrote…</i></summary><blockquote>

add vdm_new -- at eh begining (look at other comments to function eg. in the pmdk repo)
</blockquote></details>

Done.
___
*[src/vdm.c, line 19 at r14](https://reviewable.io/reviews/pmem/miniasync/33#-MuAsR9R9sSboRC8qR8c:-MuCXWXN2h3eoKS-nW1t:b-896fix) ([raw file](https://github.com/pmem/miniasync/blob/978022ebca2a946bfbd3972f162634f04c6f3374/src/vdm.c#L19)):*
<details><summary><i>Previously, wlemkows (Weronika Lewandowska) wrote…</i></summary><blockquote>

It would be nice to add description to vdm_new/delete to the man page.
</blockquote></details>

Done.
___
*[src/vdm.c, line 28 at r14](https://reviewable.io/reviews/pmem/miniasync/33#-MsEfSvFE6Zl5940pL-3-r14-28:-MuCYaPg2gaenBL-Hsib:b-896fix) ([raw file](https://github.com/pmem/miniasync/blob/978022ebca2a946bfbd3972f162634f04c6f3374/src/vdm.c#L28)):*
<details><summary><i>Previously, wlemkows (Weronika Lewandowska) wrote…</i></summary><blockquote>

null reference if user arg is null
</blockquote></details>

Done.
___
*[src/vdm_threads.c, line 17 at r14](https://reviewable.io/reviews/pmem/miniasync/33#-MuAuFlPEoTvNmf7WAnT:-MuC_GAF7fuw-eOLy2Kj:b-896fix) ([raw file](https://github.com/pmem/miniasync/blob/978022ebca2a946bfbd3972f162634f04c6f3374/src/vdm_threads.c#L17)):*
<details><summary><i>Previously, wlemkows (Weronika Lewandowska) wrote…</i></summary><blockquote>

ALL functions should have a comment above.
</blockquote></details>

Done.
___
*[src/include/libminiasync/vdm.h, line 41 at r14](https://reviewable.io/reviews/pmem/miniasync/33#-MuAz_av1PMEBf6X2VXt:-MuC_dV6B6ZbV1Ut53MU:b-896fix) ([raw file](https://github.com/pmem/miniasync/blob/978022ebca2a946bfbd3972f162634f04c6f3374/src/include/libminiasync/vdm.h#L41)):*
<details><summary><i>Previously, wlemkows (Weronika Lewandowska) wrote…</i></summary><blockquote>

wrong indentation
</blockquote></details>

Done.
___
*[src/include/libminiasync/vdm_threads.h, line 4 at r14](https://reviewable.io/reviews/pmem/miniasync/33#-MuAzs6X8rN5Puuru7vU:-MuC_klm2eAbISIm1rrU:b-896fix) ([raw file](https://github.com/pmem/miniasync/blob/978022ebca2a946bfbd3972f162634f04c6f3374/src/include/libminiasync/vdm_threads.h#L4)):*
<details><summary><i>Previously, wlemkows (Weronika Lewandowska) wrote…</i></summary><blockquote>

THREADS
</blockquote></details>

Done.
___
*[tests/memcpy_threads/test_memcpy_threads.cmake, line 4 at r14](https://reviewable.io/reviews/pmem/miniasync/33#-MuBENOk0iFP7wx7bPNt:-MuCa0tM0XIJR8_Ggatx:bwfqpsp) ([raw file](https://github.com/pmem/miniasync/blob/978022ebca2a946bfbd3972f162634f04c6f3374/tests/memcpy_threads/test_memcpy_threads.cmake#L4)):*
<details><summary><i>Previously, wlemkows (Weronika Lewandowska) wrote…</i></summary><blockquote>

Is this test for basic example?? Do you have test for basic-async?
</blockquote></details>

I copied the code from the ex_basic test and forgot to remove it. I think that we do not need a test for basic-async because the operations presented in the example are covered much better in the memcpy_threads test.


<!-- Sent from Reviewable.io -->

2022-01-25 07:06 UTC, wlemkows requested changes
> Reviewed 1 of 3 files at r11, 1 of 3 files at r12, 2 of 9 files at r13, 10 of 10 files at r15, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/miniasync/33)* status: all files reviewed, 10 unresolved discussions (waiting on @blazej-smorawski and @kswiecicki)

___
*[doc/CMakeLists.txt, line 72 at r15](https://reviewable.io/reviews/pmem/miniasync/33#-MuF20oRC_W_EQs-T6yP:-MuF20oRC_W_EQs-T6yQ:b-qltpq7) ([raw file](https://github.com/pmem/miniasync/blob/4c283ab5a27d1857c7093db4badb3a93c6c23ea9/doc/CMakeLists.txt#L72)):*
> ```CMake
> 	configure_man(miniasync_vdm.3 ${MAN_DIR}/tmp/miniasync_vdm.3.md)
> 	add_manpage_links(miniasync_vdm.3
> 		vdm_descriptor_synchronous vdm_descriptor_pthreads vdm_new vdm_delete)
> ```

"add_manpage_links" does this so that if you type "man function_name" into the console after installing the documentation on your system, you will go to the document specified in the first parameter.
Only functions that are in that document should link to it. Please verify correctness in this and other cases.
___
*[doc/miniasync_vdm.3.md.in, line 44 at r15](https://reviewable.io/reviews/pmem/miniasync/33#-MuEyrcI3jug_EcHGBNM:-MuEyrcQ6koMrmyKlubq:b5395vy) ([raw file](https://github.com/pmem/miniasync/blob/2466eddd49f7d4be76f55d508e1f346de4d930c3/doc/miniasync_vdm.3.md.in#L44)):*
> ```
> API for miniasync library forming the basis of various data movers.
> 
> `struct vdm *vdm_new(struct vdm_descriptor *descriptor);`
> ```

Please add RETURN VALUE section (look at PMDK man pages)

Also check the other man page, is the function returns a value this section should be placed.
___
*[doc/miniasync_vdm.3.md.in, line 46 at r15](https://reviewable.io/reviews/pmem/miniasync/33#-MuEz-Cc5jwEkQSwv_g2:-MuEz-Cc5jwEkQSwv_g3:bml7k5j) ([raw file](https://github.com/pmem/miniasync/blob/2466eddd49f7d4be76f55d508e1f346de4d930c3/doc/miniasync_vdm.3.md.in#L46)):*
> ```
> `struct vdm *vdm_new(struct vdm_descriptor *descriptor);`
> 
> :	Creates new instance of virtual data mover defined by the `descriptor`. It
> ```

Keep the same format as the other man pages, there we don't use a colon at the beginning.
___
*[doc/miniasync_vdm.3.md.in, line 47 at r15](https://reviewable.io/reviews/pmem/miniasync/33#-MuEz1DR7gJv_g_OGbns:-MuEz1DR7gJv_g_OGbnt:b-wy05m1) ([raw file](https://github.com/pmem/miniasync/blob/2466eddd49f7d4be76f55d508e1f346de4d930c3/doc/miniasync_vdm.3.md.in#L47)):*
> ```
> 
> :	Creates new instance of virtual data mover defined by the `descriptor`. It
> is also calling `descriptor->vdm_data_init` if it was specified in the descriptor.
> ```

Second sentence is confusing, elaborate, change or add example.
___
*[doc/miniasync_vdm_synchronous.3.md.in, line 18 at r15](https://reviewable.io/reviews/pmem/miniasync/33#-MuEw0lpDetKO3K4QspY:-MuEw0lr9uEW0MoNBhfX:ba23edn) ([raw file](https://github.com/pmem/miniasync/blob/2466eddd49f7d4be76f55d508e1f346de4d930c3/doc/miniasync_vdm_synchronous.3.md.in#L18)):*
> ```
> [SYNOPSIS](#synopsis)<br />
> [DESCRIPTION](#description)<br />
> [ERRORS](#errors)<br />
> ```

rm ERRORS
___
*[doc/miniasync_vdm_threads.3.md.in, line 70 at r14](https://reviewable.io/reviews/pmem/miniasync/33#-Mtmk6eyHIuohJAzm4H--r14-70:-MuExEZk9D1oXBuYt5We:b-1jg44w) ([raw file](https://github.com/pmem/miniasync/blob/978022ebca2a946bfbd3972f162634f04c6f3374/doc/miniasync_vdm_threads.3.md.in#L70)):*
<details><summary><i>Previously, blazej-smorawski wrote…</i></summary><blockquote>

I did not have any knowledge of existing errors here, so I left it empty. I didn't remove this header because I thought that those manpages are still in a draft stage and will be rewritten in the nearest future.
</blockquote></details>

When you write documentation, don't treat it as a draft. It usually ends up being the final version, unless you make changes to the API, then it gets revised.
___
*[CMakeLists.txt, line 26 at r11](https://reviewable.io/reviews/pmem/miniasync/33#-MuF2d533PFUz5jOAr9e:-MuF2d533PFUz5jOAr9f:bb7r2f0) ([raw file](https://github.com/pmem/miniasync/blob/2170207a20858a9881f2b67f12f513453a6133ab/CMakeLists.txt#L26)):*
> ```CMake
> 
> option(COVERAGE "run coverage test" OFF)
> option(DEVELOPER_MODE "enable developer checks" OFF)
> ```

why?
___
*[tests/memcpy_threads/memcpy_threads.c, line 172 at r15](https://reviewable.io/reviews/pmem/miniasync/33#-MuF2k2G9gbayg19UXr2:-MuF2k2G9gbayg19UXr3:bb7r2f0) ([raw file](https://github.com/pmem/miniasync/blob/2466eddd49f7d4be76f55d508e1f346de4d930c3/tests/memcpy_threads/memcpy_threads.c#L172)):*
> ```C
> 	return
> 		test_threads_memcpy_multiple_same_char(100, 10, 10) ||
> 		test_threads_memcpy_multiple_same_char(100, 2, 1 << 10) ||
> ```

why?
___
*[tests/memcpy_threads/test_memcpy_threads.cmake, line 4 at r14](https://reviewable.io/reviews/pmem/miniasync/33#-MuBENOk0iFP7wx7bPNt:-MuF06Vy4iEsIPe8EOiI:b-2tqjne) ([raw file](https://github.com/pmem/miniasync/blob/978022ebca2a946bfbd3972f162634f04c6f3374/tests/memcpy_threads/test_memcpy_threads.cmake#L4)):*
<details><summary><i>Previously, blazej-smorawski wrote…</i></summary><blockquote>

I copied the code from the ex_basic test and forgot to remove it. I think that we do not need a test for basic-async because the operations presented in the example are covered much better in the memcpy_threads test.
</blockquote></details>

We don't need to test it, but we need to at least run it during every build to make sure the example still works.


<!-- Sent from Reviewable.io -->

2022-01-25 12:24 UTC, blazej-smorawski reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/miniasync/33)* status: all files reviewed, 10 unresolved discussions (waiting on @kswiecicki and @wlemkows)

___
*[doc/CMakeLists.txt, line 72 at r15](https://reviewable.io/reviews/pmem/miniasync/33#-MuF20oRC_W_EQs-T6yP:-MuFxpr54oKJhIM8kUOx:b-z0o91a) ([raw file](https://github.com/pmem/miniasync/blob/4c283ab5a27d1857c7093db4badb3a93c6c23ea9/doc/CMakeLists.txt#L72)):*
<details><summary><i>Previously, wlemkows (Weronika Lewandowska) wrote…</i></summary><blockquote>

"add_manpage_links" does this so that if you type "man function_name" into the console after installing the documentation on your system, you will go to the document specified in the first parameter.
Only functions that are in that document should link to it. Please verify correctness in this and other cases.
</blockquote></details>

Sure, should be fixed now.
___
*[doc/miniasync_vdm.3.md.in, line 44 at r15](https://reviewable.io/reviews/pmem/miniasync/33#-MuEyrcI3jug_EcHGBNM:-MuG3KeD1O-RDNoOZ-9g:b-896fix) ([raw file](https://github.com/pmem/miniasync/blob/2466eddd49f7d4be76f55d508e1f346de4d930c3/doc/miniasync_vdm.3.md.in#L44)):*
<details><summary><i>Previously, wlemkows (Weronika Lewandowska) wrote…</i></summary><blockquote>

Please add RETURN VALUE section (look at PMDK man pages)

Also check the other man page, is the function returns a value this section should be placed.
</blockquote></details>

Done.
___
*[doc/miniasync_vdm.3.md.in, line 46 at r15](https://reviewable.io/reviews/pmem/miniasync/33#-MuEz-Cc5jwEkQSwv_g2:-MuG3MH6-ORqgluGKdUo:b-896fix) ([raw file](https://github.com/pmem/miniasync/blob/2466eddd49f7d4be76f55d508e1f346de4d930c3/doc/miniasync_vdm.3.md.in#L46)):*
<details><summary><i>Previously, wlemkows (Weronika Lewandowska) wrote…</i></summary><blockquote>

Keep the same format as the other man pages, there we don't use a colon at the beginning.
</blockquote></details>

Done.
___
*[doc/miniasync_vdm.3.md.in, line 47 at r15](https://reviewable.io/reviews/pmem/miniasync/33#-MuEz1DR7gJv_g_OGbns:-MuG42tmDDxh1v_maOIf:b-896fix) ([raw file](https://github.com/pmem/miniasync/blob/2466eddd49f7d4be76f55d508e1f346de4d930c3/doc/miniasync_vdm.3.md.in#L47)):*
<details><summary><i>Previously, wlemkows (Weronika Lewandowska) wrote…</i></summary><blockquote>

Second sentence is confusing, elaborate, change or add example.
</blockquote></details>

Done.
___
*[doc/miniasync_vdm_synchronous.3.md.in, line 18 at r15](https://reviewable.io/reviews/pmem/miniasync/33#-MuEw0lpDetKO3K4QspY:-MuG4uc5BObAQI4fGDDp:b-896fix) ([raw file](https://github.com/pmem/miniasync/blob/2466eddd49f7d4be76f55d508e1f346de4d930c3/doc/miniasync_vdm_synchronous.3.md.in#L18)):*
<details><summary><i>Previously, wlemkows (Weronika Lewandowska) wrote…</i></summary><blockquote>

rm ERRORS
</blockquote></details>

Done.
___
*[doc/miniasync_vdm_threads.3.md.in, line 70 at r14](https://reviewable.io/reviews/pmem/miniasync/33#-Mtmk6eyHIuohJAzm4H--r14-70:-MuG4wwW4jL87K205OqK:b-mvq2v4) ([raw file](https://github.com/pmem/miniasync/blob/978022ebca2a946bfbd3972f162634f04c6f3374/doc/miniasync_vdm_threads.3.md.in#L70)):*
<details><summary><i>Previously, wlemkows (Weronika Lewandowska) wrote…</i></summary><blockquote>

When you write documentation, don't treat it as a draft. It usually ends up being the final version, unless you make changes to the API, then it gets revised.
</blockquote></details>

Ok, I will remember that now.
___
*[CMakeLists.txt, line 26 at r11](https://reviewable.io/reviews/pmem/miniasync/33#-MuF2d533PFUz5jOAr9e:-MuG9mEt2zCevAQOkRwU:bdwt87v) ([raw file](https://github.com/pmem/miniasync/blob/2170207a20858a9881f2b67f12f513453a6133ab/CMakeLists.txt#L26)):*
<details><summary><i>Previously, wlemkows (Weronika Lewandowska) wrote…</i></summary><blockquote>

why?
</blockquote></details>

I changed it back to OFF, because it's like that in master and was previously changed by me to ON during some tests early on.
___
*[tests/memcpy_threads/memcpy_threads.c, line 172 at r15](https://reviewable.io/reviews/pmem/miniasync/33#-MuF2k2G9gbayg19UXr2:-MuG6Iqf7o_cjYZRRx8L:bpwygss) ([raw file](https://github.com/pmem/miniasync/blob/2466eddd49f7d4be76f55d508e1f346de4d930c3/tests/memcpy_threads/memcpy_threads.c#L172)):*
<details><summary><i>Previously, wlemkows (Weronika Lewandowska) wrote…</i></summary><blockquote>

why?
</blockquote></details>

I wanted to have a case of 2 memcpys which is more likely to show issues with fast loops and frequent calls of runtime_wait.
___
*[tests/memcpy_threads/test_memcpy_threads.cmake, line 4 at r14](https://reviewable.io/reviews/pmem/miniasync/33#-MuBENOk0iFP7wx7bPNt:-MuG8rR154yf-5EMU_fo:b61g8ii) ([raw file](https://github.com/pmem/miniasync/blob/978022ebca2a946bfbd3972f162634f04c6f3374/tests/memcpy_threads/test_memcpy_threads.cmake#L4)):*
<details><summary><i>Previously, wlemkows (Weronika Lewandowska) wrote…</i></summary><blockquote>

We don't need to test it, but we need to at least run it during every build to make sure the example still works.
</blockquote></details>

Oh, I haven't thought about that. Added it.


<!-- Sent from Reviewable.io -->

2022-01-25 12:41 UTC, wlemkows requested changes
> Reviewed 2 of 6 files at r16.
> *[Reviewable](https://reviewable.io/reviews/pmem/miniasync/33)* status: 37 of 41 files reviewed, 6 unresolved discussions (waiting on @blazej-smorawski, @kswiecicki, and @wlemkows)

___
*[doc/miniasync_vdm.3.md.in, line 18 at r15](https://reviewable.io/reviews/pmem/miniasync/33#-MuGFIQN5eDMP71pKkEj:-MuGFIQPD3d-d_GRzUXY:bom938g) ([raw file](https://github.com/pmem/miniasync/blob/2466eddd49f7d4be76f55d508e1f346de4d930c3/doc/miniasync_vdm.3.md.in#L18)):*
> ```
> [SYNOPSIS](#synopsis)<br />
> [DESCRIPTION](#description)<br />
> [ERRORS](#errors)<br />
> ```

RETURN VALUE is missing now


<!-- Sent from Reviewable.io -->

2022-01-25 12:42 UTC, wlemkows requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/miniasync/33)* status: 37 of 41 files reviewed, 3 unresolved discussions (waiting on @blazej-smorawski, @kswiecicki, and @wlemkows)

___
*[doc/miniasync_vdm_synchronous.3.md.in, line 18 at r15](https://reviewable.io/reviews/pmem/miniasync/33#-MuGFaf55rp1bXBMORTy:-MuGFaf55rp1bXBMORTz:b3kqx) ([raw file](https://github.com/pmem/miniasync/blob/2466eddd49f7d4be76f55d508e1f346de4d930c3/doc/miniasync_vdm_synchronous.3.md.in#L18)):*
> ```
> [SYNOPSIS](#synopsis)<br />
> [DESCRIPTION](#description)<br />
> [ERRORS](#errors)<br />
> ```

.


<!-- Sent from Reviewable.io -->

2022-01-25 12:43 UTC, wlemkows requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/miniasync/33)* status: 37 of 41 files reviewed, 4 unresolved discussions (waiting on @blazej-smorawski, @kswiecicki, and @wlemkows)

___
*[doc/miniasync_vdm_threads.3.md.in, line 67 at r16](https://reviewable.io/reviews/pmem/miniasync/33#-MuGFggn2QoUWF4pR2gf:-MuGFggoDVrsiywA5rzZ:b-8047tg) ([raw file](https://github.com/pmem/miniasync/blob/51d41d191b442e5ddd35b029b11c218444e19291/doc/miniasync_vdm_threads.3.md.in#L67)):*
> ```
> `runtime_wait_multiple` if the count of operations is bigger than size of the queue.
> 
> # RETURN VALE #
> ```

VALUE


<!-- Sent from Reviewable.io -->

2022-01-25 12:50 UTC, wlemkows requested changes
> Reviewed 1 of 6 files at r16, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/miniasync/33)* status: 38 of 41 files reviewed, 5 unresolved discussions (waiting on @blazej-smorawski, @kswiecicki, and @wlemkows)

___
*[doc/miniasync_vdm.3.md.in, line 63 at r16](https://reviewable.io/reviews/pmem/miniasync/33#-MuGGkDH6f6shYb_tJwZ:-MuGGkDJDrBfSL3-8-lS:b-ecve9o) ([raw file](https://github.com/pmem/miniasync/blob/51d41d191b442e5ddd35b029b11c218444e19291/doc/miniasync_vdm.3.md.in#L63)):*
> ```
> 
> The `vdm_new` returns pointer to a `struct vdm` or **NULL** if the allocation of
> `struct vdm` failed, passed descriptor is **NULL** or calling
> ```

I do not get it. Please refactor.
You can't suddenly point to some "init". Do we explain anywhere beforehand what a descriptor init is?


<!-- Sent from Reviewable.io -->

2022-01-25 12:51 UTC, wlemkows reviewed
> Reviewed 3 of 6 files at r16.
> *[Reviewable](https://reviewable.io/reviews/pmem/miniasync/33)* status: all files reviewed, 5 unresolved discussions (waiting on @blazej-smorawski and @kswiecicki)



<!-- Sent from Reviewable.io -->

2022-01-26 07:07 UTC, wlemkows commented on doc/miniasync_vdm.3.md.in
> +and `vdm_data_fini`. They are responsible for initializing and finalizing data needed
I've thought about it, and I don't think it's necessary to mention these functions in the descriptor.

2022-01-26 07:07 UTC, wlemkows commented on doc/miniasync_vdm.3.md.in
> +creating instance of vdm with `vdm_descriptor_threads` calls a procedure that creates
use this format for functions reference: \*\*vdm_descriptor_threads\*\*(3)

2022-01-26 07:08 UTC, wlemkows commented on doc/miniasync_vdm.3.md.in
> +Initializes and returns a new memcpy future based on the virtual data mover instance `vdm` and
Documentation should explain ADD function parameters and what this function does. In this case eg. we have no idea what the flags parameter is for.

2022-01-26 07:08 UTC, wlemkows commented on doc/miniasync_vdm.3.md.in
> +The `vdm_new` returns pointer to a `struct vdm` or **NULL** if the allocation of
\*\*vdm_new\*\*

2022-01-26 07:08 UTC, wlemkows commented on doc/miniasync_vdm.3.md.in
> +`struct vdm` failed, passed descriptor is **NULL** or calling `vdm_data_init` failed.
mentioning vdm_data_init sounds like an implementation detail to me

2022-01-26 07:11 UTC, wlemkows commented on doc/miniasync_vdm_threads.3.md.in
> +```c
For one line code use single `

2022-01-26 07:12 UTC, wlemkows commented on doc/miniasync_vdm.3.md.in
> +Initializes and returns a new memcpy future based on the virtual data mover instance `vdm` and
This commit ref to `struct vdm_memcpy_future vdm_memcpy(struct vdm *vdm, void *dest, void *src, size_t n, uint64_t flags);`

2022-01-26 07:13 UTC, wlemkows reviewed
> Reviewed 3 of 3 files at r17, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/miniasync/33)* status: all files reviewed, 11 unresolved discussions (waiting on @blazej-smorawski, @kswiecicki, and @pbalcer)



<!-- Sent from Reviewable.io -->

2022-01-26 09:39 UTC, pbalcer approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/miniasync/33)* status: all files reviewed, 11 unresolved discussions (waiting on @blazej-smorawski and @kswiecicki)



<!-- Sent from Reviewable.io -->

2022-01-26 13:35 UTC, wlemkows reviewed
> Reviewed 3 of 3 files at r18, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/miniasync/33)* status: all files reviewed, 10 unresolved discussions (waiting on @blazej-smorawski and @kswiecicki)



<!-- Sent from Reviewable.io -->

2022-01-26 13:36 UTC, merged