masync: fix memory leaks and coverity issues
pmem/miniasync pull request #37
Opened 2022-01-27 08:29 UTC by blazej-smorawski

2022-01-27 09:24 UTC, pbalcer commented on src/vdm.c
> +	if (descriptor == NULL)
No, this type of check is almost never a good idea. Errors should be caught at the earliest possible moment. This NULL-check should be resolved at the call site.

2022-01-27 09:24 UTC, pbalcer commented on tests/memcpy_threads/memcpy_threads.c
>  test_threads_memcpy_multiple_same_char(unsigned memcpy_count,
this function and the one below are almost identical. Try to abstract away the boilerplate.

2022-01-27 09:24 UTC, pbalcer commented on tests/memcpy_threads/memcpy_threads.c
> +				free(sources[j]);
use MALLOC/FREE in tests.

2022-01-27 09:24 UTC, pbalcer commented on tests/memcpy_threads/memcpy_threads.c
> +			/* Cleanup */
```
ret = 1;
goto cleanup;
```
?

2022-01-27 09:32 UTC, wlemkows reviewed
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/miniasync/37)* status: all files reviewed, 4 unresolved discussions (waiting on @blazej-smorawski)



<!-- Sent from Reviewable.io -->

2022-01-28 07:39 UTC, blazej-smorawski reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/miniasync/37)* status: 1 of 4 files reviewed, 4 unresolved discussions (waiting on @pbalcer and @wlemkows)

___
*[src/vdm.c, line 21 at r1](https://reviewable.io/reviews/pmem/miniasync/37#-MuPdxbHLeh7fnOzbeRg-r1-21:-MuQ1kns4eklRV1UiRgs:b-896fix) ([raw file](https://github.com/pmem/miniasync/blob/915ce1887e02e45a67d4c5683ebc859299bd3623/src/vdm.c#L21)):*
<details><summary><i>Previously, pbalcer (Piotr Balcer) wrote…</i></summary><blockquote>

No, this type of check is almost never a good idea. Errors should be caught at the earliest possible moment. This NULL-check should be resolved at the call site.
</blockquote></details>

Done.
___
*[tests/memcpy_threads/memcpy_threads.c, line 11 at r1](https://reviewable.io/reviews/pmem/miniasync/37#-MuPdxbHLeh7fnOzbeRi-r1-11:-MuQ1leN5RF3hXegm48n:b-896fix) ([raw file](https://github.com/pmem/miniasync/blob/915ce1887e02e45a67d4c5683ebc859299bd3623/tests/memcpy_threads/memcpy_threads.c#L11)):*
<details><summary><i>Previously, pbalcer (Piotr Balcer) wrote…</i></summary><blockquote>

this function and the one below are almost identical. Try to abstract away the boilerplate.
</blockquote></details>

Done.
___
*[tests/memcpy_threads/memcpy_threads.c, line 68 at r1](https://reviewable.io/reviews/pmem/miniasync/37#-MuPdxbHLeh7fnOzbeRi-r1-68:-MuQ1mSWCALGN9R0_zVc:b-896fix) ([raw file](https://github.com/pmem/miniasync/blob/915ce1887e02e45a67d4c5683ebc859299bd3623/tests/memcpy_threads/memcpy_threads.c#L68)):*
<details><summary><i>Previously, pbalcer (Piotr Balcer) wrote…</i></summary><blockquote>

```
ret = 1;
goto cleanup;
```
?
</blockquote></details>

Done.
___
*[tests/memcpy_threads/memcpy_threads.c, line 70 at r1](https://reviewable.io/reviews/pmem/miniasync/37#-MuPdxbHLeh7fnOzbeRi-r1-70:-MuQ1xNy1J-AZJa4L3j9:b-896fix) ([raw file](https://github.com/pmem/miniasync/blob/915ce1887e02e45a67d4c5683ebc859299bd3623/tests/memcpy_threads/memcpy_threads.c#L70)):*
<details><summary><i>Previously, pbalcer (Piotr Balcer) wrote…</i></summary><blockquote>

use MALLOC/FREE in tests.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-01-28 12:15 UTC, pbalcer requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/miniasync/37)* status: 1 of 4 files reviewed, 2 unresolved discussions (waiting on @blazej-smorawski, @pbalcer, and @wlemkows)

___
*[tests/memcpy_threads/memcpy_threads.c, line 13 at r2](https://reviewable.io/reviews/pmem/miniasync/37#-MuVb-Z93Yj2LO8Nnp3k:-MuVb-Z93Yj2LO8Nnp3l:b-fxhrje) ([raw file](https://github.com/pmem/miniasync/blob/426052b87f92c337f8c6ca0906e2a16926941281/tests/memcpy_threads/memcpy_threads.c#L13)):*
> ```C
>  * test_threads_memcpy_multiple -- test multiple memcpy operations
>  * on a specific descriptor.
>  * test_type = 0 => sequence
> ```

use an enum


<!-- Sent from Reviewable.io -->

2022-01-28 13:41 UTC, kswiecicki commented
___
*[src/vdm.c, line 2 at r2](https://reviewable.io/reviews/pmem/miniasync/37#-MuVua5dCHigbp4AH51A:-MuVua5dCHigbp4AH51B:b-aya5f3) ([raw file](https://github.com/pmem/miniasync/blob/426052b87f92c337f8c6ca0906e2a16926941281/src/vdm.c#L2)):*
> ```C
> // SPDX-License-Identifier: BSD-3-Clause
> /* Copyright 2021, Intel Corporation */
> ```

2022.
I'm not sure how did this pass license check.



_Code quote:_
```C
 2021
```


<!-- Sent from Reviewable.io -->

2022-01-31 07:53 UTC, blazej-smorawski reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/miniasync/37)* status: 1 of 4 files reviewed, 1 unresolved discussion (waiting on @kswiecicki, @pbalcer, and @wlemkows)

___
*[src/vdm.c, line 2 at r2](https://reviewable.io/reviews/pmem/miniasync/37#-MuVua5dCHigbp4AH51A:-Muj6hCM8y7k8K22yRnX:b-896fix) ([raw file](https://github.com/pmem/miniasync/blob/426052b87f92c337f8c6ca0906e2a16926941281/src/vdm.c#L2)):*
<details><summary><i>Previously, kswiecicki (Krzysztof Święcicki) wrote…</i></summary><blockquote>

2022.
I'm not sure how did this pass license check.
</blockquote></details>

Done.
___
*[tests/memcpy_threads/memcpy_threads.c, line 13 at r2](https://reviewable.io/reviews/pmem/miniasync/37#-MuVb-Z93Yj2LO8Nnp3k:-Muj6jBTAqfToQT08XPQ:b-896fix) ([raw file](https://github.com/pmem/miniasync/blob/426052b87f92c337f8c6ca0906e2a16926941281/tests/memcpy_threads/memcpy_threads.c#L13)):*
<details><summary><i>Previously, pbalcer (Piotr Balcer) wrote…</i></summary><blockquote>

use an enum
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-01-31 09:03 UTC, pbalcer approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/pmem/miniasync/37#-:-MujMtWx0cmFYSZsl-2X:bnfp4nl)* status: 1 of 4 files reviewed, all discussions resolved (waiting on @kswiecicki, @pbalcer, and @wlemkows)



<!-- Sent from Reviewable.io -->

2022-01-31 09:22 UTC, kswiecicki commented
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>





<!-- Sent from Reviewable.io -->

2022-01-31 09:23 UTC, merged