masync: expand the documentation
pmem/miniasync pull request #57
Opened 2022-02-25 11:04 UTC by kswiecicki

2022-02-25 13:44 UTC, lukaszstolarczuk reviewed
> Reviewed 9 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/miniasync/57)* status: 9 of 10 files reviewed, 24 unresolved discussions (waiting on @kswiecicki and @lukaszstolarczuk)

*[a discussion](https://reviewable.io/reviews/pmem/miniasync/57#-MwkoQKTB6mPQo7xXoHd:-MwkoQKTB6mPQo7xXoHe:b8c90mv) (no related file):*
actually... why are all of the doc files with `.md.in` extension and are configured in CMake (using `configure_file` function)? I don't believe they include any variables/dynamic content to build in CMake...

---
___
*[doc/future_context_get_data.3.md.in, line 36 at r1](https://reviewable.io/reviews/pmem/miniasync/57#-MwkohHOBw2xEH1QptSd:-MwkohHOBw2xEH1QptSe:bu2s1zc) ([raw file](https://github.com/pmem/miniasync/blob/ec38579167a5ad1ef82f39be096e5d49f8fdb9e8/doc/future_context_get_data.3.md.in#L36)):*
> ```
> ```
> 
> For general description of future API see **miniasync_future**(7).
> ```

miniasync_future is a `(3)` I believe - pls fix them all (or update the manpage section)
___
*[doc/future_context_get_size.3.md.in, line 24 at r1](https://reviewable.io/reviews/pmem/miniasync/57#-MwkovyG4iX0C9nh5g7d:-MwkovyG4iX0C9nh5g7e:b-d96egc) ([raw file](https://github.com/pmem/miniasync/blob/ec38579167a5ad1ef82f39be096e5d49f8fdb9e8/doc/future_context_get_size.3.md.in#L24)):*
> ```
> # NAME #
> 
> **future_context_get_size**() - get the size of future data and output
> ```

combined/total size (?)
___
*[doc/future_context_get_size.3.md.in, line 40 at r1](https://reviewable.io/reviews/pmem/miniasync/57#-Mwkp89MDarCaL-7Zwxv:-Mwkp89MDarCaL-7Zwxw:bs0mfe3) ([raw file](https://github.com/pmem/miniasync/blob/ec38579167a5ad1ef82f39be096e5d49f8fdb9e8/doc/future_context_get_size.3.md.in#L40)):*
> ```
> # DESCRIPTION #
> 
> The **future_context_get_size**() function reads the size of the data and output
> ```

data and output structs (?)
___
*[doc/future_poll.3.md.in, line 55 at r1](https://reviewable.io/reviews/pmem/miniasync/57#-MwksCmZEzJ5Eu0v4-im:-MwksCmZEzJ5Eu0v4-in:bpvq1kf) ([raw file](https://github.com/pmem/miniasync/blob/ec38579167a5ad1ef82f39be096e5d49f8fdb9e8/doc/future_poll.3.md.in#L55)):*
> ```
> task function. Future notifiers can be used to notify the caller that some progress
> can be made and the future should be polled again. This can be used to avoid busy
> polling.
> ```

what are notifiers exactly? what kind of notifiers do you support? perhaps they are described somewhere...?
___
*[doc/future_poll.3.md.in, line 68 at r1](https://reviewable.io/reviews/pmem/miniasync/57#-MwkmpWR8j42jdTvRO5J:-MwkmpWR8j42jdTvRO5K:b-sg1s9f) ([raw file](https://github.com/pmem/miniasync/blob/ec38579167a5ad1ef82f39be096e5d49f8fdb9e8/doc/future_poll.3.md.in#L68)):*
> ```
> * **FUTURE_STATE_RUNNING** - future task is in progress
> 
> * **FFUTURE_STATE_COMPLETE** - future task was completed
> ```

`**FF...`
___
*[doc/miniasync_future.3.md.in, line 44 at r1](https://reviewable.io/reviews/pmem/miniasync/57#-MwkwFdv6jmTmlODKklA:-MwkwFdv6jmTmlODKklB:bonxz6q) ([raw file](https://github.com/pmem/miniasync/blob/ec38579167a5ad1ef82f39be096e5d49f8fdb9e8/doc/miniasync_future.3.md.in#L44)):*
> ```
> FUTURE_AS_RUNNABLE(_futurep)
> FUTURE_OUTPUT(_futurep)
> FUTURE_BUSY_POLL(_futurep)
> ```

output and busy_poll are not described
___
*[doc/miniasync_future.3.md.in, line 65 at r1](https://reviewable.io/reviews/pmem/miniasync/57#-Mwksmws-g0QJ9Aflvq-:-Mwksmws-g0QJ9Aflvq0:bqcqtof) ([raw file](https://github.com/pmem/miniasync/blob/ec38579167a5ad1ef82f39be096e5d49f8fdb9e8/doc/miniasync_future.3.md.in#L65)):*
> ```
> * the size of the data and output structures (both can be 0)
> 
> A future definition must begin an instance of the *struct future* type, which
> ```

begin (with?) an ...
___
*[doc/miniasync_future.3.md.in, line 68 at r1](https://reviewable.io/reviews/pmem/miniasync/57#-MwksxXD69n5nXTAGTlM:-MwksxXD69n5nXTAGTlN:b-tfa6oa) ([raw file](https://github.com/pmem/miniasync/blob/ec38579167a5ad1ef82f39be096e5d49f8fdb9e8/doc/miniasync_future.3.md.in#L68)):*
> ```
> contains all common metadata for all futures, followed by the structures for
> data and output. The library provides convenience macros to simplify
> the definition of user-defined future types.
> ```

did you mean `FUTURE()` - perhaps mention it here...?
___
*[doc/miniasync_future.3.md.in, line 101 at r1](https://reviewable.io/reviews/pmem/miniasync/57#-MwkuGF6C0BCwQEGBaik:-MwkuGF6C0BCwQEGBail:bi3ykzm) ([raw file](https://github.com/pmem/miniasync/blob/ec38579167a5ad1ef82f39be096e5d49f8fdb9e8/doc/miniasync_future.3.md.in#L101)):*
> ```
> **future_context_get_data**(3) function. Similarly, the output of the future task can be
> retrieved using **future_context_get_output**(3) function. When the user has no need for input
> or output data, *_data_type* and *_output_type* can be defined as empty structures.
> ```

FYI, on the contrary, in the `basic` example there's a special dummy field to avoid empty struct ( https://github.com/pmem/miniasync/blob/master/examples/basic/basic.c#L27 ) :wink: 
___
*[doc/miniasync_future.3.md.in, line 110 at r1](https://reviewable.io/reviews/pmem/miniasync/57#-MwkwbWM3HYhhWZkHL4g:-MwkwbWM3HYhhWZkHL4h:bcxv7yi) ([raw file](https://github.com/pmem/miniasync/blob/ec38579167a5ad1ef82f39be096e5d49f8fdb9e8/doc/miniasync_future.3.md.in#L110)):*
> ```
> entries. Those entries will be executed sequentially in the order they were defined in the
> chained future data structure. Chained future should declare members of its data structure
> with this macro.
> ```

`with` -> `using` (imho, it seems to fit better here) 
___
*[doc/miniasync_future.3.md.in, line 110 at r1](https://reviewable.io/reviews/pmem/miniasync/57#-Mwkwk2yEhWw_DRbv_sO:-Mwkwk2zCejWjWlZ5EDz:bnf08ge) ([raw file](https://github.com/pmem/miniasync/blob/ec38579167a5ad1ef82f39be096e5d49f8fdb9e8/doc/miniasync_future.3.md.in#L110)):*
> ```
> entries. Those entries will be executed sequentially in the order they were defined in the
> chained future data structure. Chained future should declare members of its data structure
> with this macro.
> ```

based on this description I couldn't figure out that these entries should be a part of the data structure for a FUTURE (maybe it's me, maybe it's the wording)
___
*[doc/miniasync_future.3.md.in, line 112 at r1](https://reviewable.io/reviews/pmem/miniasync/57#-Mwl-qdE8IkG3m8i0TZu:-Mwl-qdF7FTLf5JaFkii:b-35u4vq) ([raw file](https://github.com/pmem/miniasync/blob/ec38579167a5ad1ef82f39be096e5d49f8fdb9e8/doc/miniasync_future.3.md.in#L112)):*
> ```
> with this macro.
> 
> **FUTURE_CHAIN_ENTRY_INIT(_entry, _fut, _map, _map_arg)** macro initializes the chained future
> ```

do I have to init all entries?
___
*[doc/miniasync_future.3.md.in, line 116 at r1](https://reviewable.io/reviews/pmem/miniasync/57#-MwkyfnKBDdB8piQ9wP8:-MwkyfnKBDdB8piQ9wP9:bpyscfa) ([raw file](https://github.com/pmem/miniasync/blob/ec38579167a5ad1ef82f39be096e5d49f8fdb9e8/doc/miniasync_future.3.md.in#L116)):*
> ```
> function *_map* and the argument for the mapping function *_map_arg*. *_fut* can either be the
> instance of the future defined using **FUTURE(_name, _data_type, _output_type)** macro or a virtual
> data mover future. *_map* function must be of the *future_map_fn* type, it should define the mapping
> ```

what will happen if I pass NULL as `_map`? will the next future get any context?
___
*[doc/miniasync_future.3.md.in, line 118 at r1](https://reviewable.io/reviews/pmem/miniasync/57#-MwkyQHB9AW3ZnHTA1-J:-MwkyQHB9AW3ZnHTA1-K:btuvc3s) ([raw file](https://github.com/pmem/miniasync/blob/ec38579167a5ad1ef82f39be096e5d49f8fdb9e8/doc/miniasync_future.3.md.in#L118)):*
> ```
> data mover future. *_map* function must be of the *future_map_fn* type, it should define the mapping
> behavior of the data and output between chained future entry *_entry* that has finished and the
> chained future entry that is about to start execution.
> ```

`... to start.` or `... to start its execution.`
___
*[doc [...]

2022-02-28 07:09 UTC, DamianDuy commented on doc/runtime_wait.3.md
> +The **runtime_wait_multiple**() function works similar the **runtime_wait**() function
I think it should be `similar to the`

2022-03-03 14:04 UTC, pbalcer requested changes
I think we should merge this patch once it's complete, but not necessarily "perfect". Then we can refine the man pages as we go.

> *[Reviewable](https://reviewable.io/reviews/pmem/miniasync/57#-:-MxF4q2E6Yghui0hTSya:b-9vcu9q)* status: 0 of 24 files reviewed, 30 unresolved discussions (waiting on @DamianDuy, @kswiecicki, @lukaszstolarczuk, and @pbalcer)

___
*[doc/data_mover_dml_get_vdm.3.md, line 45 at r4](https://reviewable.io/reviews/pmem/miniasync/57#-MxEyyiy9UsWo1_MfZr6:-MxEyyiy9UsWo1_MfZr7:bg0b8wh) ([raw file](https://github.com/pmem/miniasync/blob/a00119841404be26030b6844880289670ac1984d/doc/data_mover_dml_get_vdm.3.md#L45)):*
> ```Markdown
> ```
> 
> For general description of **DML** data mover API, see **miniasync_vdm_synchronous**(7).
> ```

`miniasync_vdm_dml` ?
___
*[doc/miniasync_runtime.7.md, line 37 at r4](https://reviewable.io/reviews/pmem/miniasync/57#-MxF1C-KBpBJL4r7vBFG:-MxF1C-KBpBJL4r7vBFH:b-aulyst) ([raw file](https://github.com/pmem/miniasync/blob/a00119841404be26030b6844880289670ac1984d/doc/miniasync_runtime.7.md#L37)):*
> ```Markdown
> # DESCRIPTION #
> 
> Runtime is an abstraction for the future polling management. It should be used
> ```

runtime is specifically not an abstraction. It's an implementation.
___
*[doc/miniasync_runtime.7.md, line 42 at r4](https://reviewable.io/reviews/pmem/miniasync/57#-MxF1S-K5QmDVLu0ZWpI:-MxF1S-K5QmDVLu0ZWpJ:byvvbhe) ([raw file](https://github.com/pmem/miniasync/blob/a00119841404be26030b6844880289670ac1984d/doc/miniasync_runtime.7.md#L42)):*
> ```Markdown
> **miniasync**(7) runtime provides methods for efficient polling of single or
> multiple futures, **runtime_wait**(3) and **runtime_wait_multiple** respectively.
> It makes use of waker notifier feature to optimise future polling behavior. Thread calling
> ```

optimize
___
*[doc/miniasync_runtime.7.md, line 43 at r4](https://reviewable.io/reviews/pmem/miniasync/57#-MxF1Zrc0py7uwquxqv8:-MxF1Zrd8jnLhZftEUpE:b4gl69s) ([raw file](https://github.com/pmem/miniasync/blob/a00119841404be26030b6844880289670ac1984d/doc/miniasync_runtime.7.md#L43)):*
> ```Markdown
> multiple futures, **runtime_wait**(3) and **runtime_wait_multiple** respectively.
> It makes use of waker notifier feature to optimise future polling behavior. Thread calling
> one of the wait functions polls each provided future once and then goes to sleep for
> ```

`polls each future until no further progress can be made, and then goes to sleep` this is more generic.

Right now the runtime will spin poll each function 1k times before going to sleep. And in the future we might be able to implement something to optimize this more.
___
*[doc/miniasync_future.3.md.in, line 101 at r1](https://reviewable.io/reviews/pmem/miniasync/57#-MwkuGF6C0BCwQEGBaik:-MxF0FZf55eUJ7JKsuuQ:b-xmond5) ([raw file](https://github.com/pmem/miniasync/blob/ec38579167a5ad1ef82f39be096e5d49f8fdb9e8/doc/miniasync_future.3.md.in#L101)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

FYI, on the contrary, in the `basic` example there's a special dummy field to avoid empty struct ( https://github.com/pmem/miniasync/blob/master/examples/basic/basic.c#L27 ) :wink: 
</blockquote></details>

that's to avoid a warning ;) afair empty structs are technically speaking a gnu extension.
___
*[doc/miniasync_future.3.md.in, line 112 at r1](https://reviewable.io/reviews/pmem/miniasync/57#-Mwl-qdE8IkG3m8i0TZu:-MxF0TAXD7vj6e6Al5m1:bb7sa0c) ([raw file](https://github.com/pmem/miniasync/blob/ec38579167a5ad1ef82f39be096e5d49f8fdb9e8/doc/miniasync_future.3.md.in#L112)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

do I have to init all entries?
</blockquote></details>

yes.
___
*[doc/miniasync_future.3.md.in, line 116 at r1](https://reviewable.io/reviews/pmem/miniasync/57#-MwkyfnKBDdB8piQ9wP8:-MxF0XJc794RKgcSUVP3:bq7jqu1) ([raw file](https://github.com/pmem/miniasync/blob/ec38579167a5ad1ef82f39be096e5d49f8fdb9e8/doc/miniasync_future.3.md.in#L116)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

what will happen if I pass NULL as `_map`? will the next future get any context?
</blockquote></details>

just the future's local state in its own data struct.
___
*[doc/miniasync_vdm_dml.7.md, line 45 at r4](https://reviewable.io/reviews/pmem/miniasync/57#-MxF2Qf22jcf5mc_TFaH:-MxF2Qf22jcf5mc_TFaI:bmsnmhg) ([raw file](https://github.com/pmem/miniasync/blob/a00119841404be26030b6844880289670ac1984d/doc/miniasync_vdm_dml.7.md#L45)):*
> ```Markdown
> `struct vdm_descriptor *vdm_descriptor_dml(void);`
> 
> :	Data Mover Library implementation of virtual data mover. It is a non-blocking copy operation.
> ```

DML nor virtual data mover are not "a non-blocking copy operation"


<!-- Sent from Reviewable.io -->

2022-03-04 13:55 UTC, kswiecicki commented
___
*[doc/runtime_delete.3.in, line 1 at r1](https://reviewable.io/reviews/pmem/miniasync/57#-MwknrRiEsoWRF7EkX07:-MxKCbTEBS410kz1yjIL:b-896fix) ([raw file](https://github.com/pmem/miniasync/blob/ec38579167a5ad1ef82f39be096e5d49f8fdb9e8/doc/runtime_delete.3.in#L1)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

I think you don't need to do this link - it's done in CMake

also - update CMake, I guess :wink: 
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-03-04 13:56 UTC, kswiecicki commented
*[a discussion](https://reviewable.io/reviews/pmem/miniasync/57#-MwkoQKTB6mPQo7xXoHd:-MxKCgLI-JeYRbigLKWT:b-39ilu2) (no related file):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

actually... why are all of the doc files with `.md.in` extension and are configured in CMake (using `configure_file` function)? I don't believe they include any variables/dynamic content to build in CMake...
</blockquote></details>

You are right, we have had it like that just in case we would need dynamic content in our manpages.
I've removed the `configure_file` thing.

---


<!-- Sent from Reviewable.io -->

2022-03-04 13:56 UTC, kswiecicki commented
___
*[doc/data_mover_dml_get_vdm.3.md, line 45 at r4](https://reviewable.io/reviews/pmem/miniasync/57#-MxEyyiy9UsWo1_MfZr6:-MxKCzXk8OH6GNap9FXr:b-896fix) ([raw file](https://github.com/pmem/miniasync/blob/a00119841404be26030b6844880289670ac1984d/doc/data_mover_dml_get_vdm.3.md#L45)):*
<details><summary><i>Previously, pbalcer (Piotr Balcer) wrote…</i></summary><blockquote>

`miniasync_vdm_dml` ?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-03-04 13:59 UTC, kswiecicki commented
___
*[doc/future_context_get_data.3.md.in, line 36 at r1](https://reviewable.io/reviews/pmem/miniasync/57#-MwkohHOBw2xEH1QptSd:-MxKD-_x1IrkTZT7JOl5:b-493acd) ([raw file](https://github.com/pmem/miniasync/blob/ec38579167a5ad1ef82f39be096e5d49f8fdb9e8/doc/future_context_get_data.3.md.in#L36)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

miniasync_future is a `(3)` I believe - pls fix them all (or update the manpage section)
</blockquote></details>

We have decided to make a manpage for each function.
`miniasync_future/vdm/runtime` and the like are now labelled with (7), they describe only the feature and macros they provide.


<!-- Sent from Reviewable.io -->

2022-03-04 13:59 UTC, kswiecicki commented
___
*[doc/future_context_get_size.3.md.in, line 24 at r1](https://reviewable.io/reviews/pmem/miniasync/57#-MwkovyG4iX0C9nh5g7d:-MxKDbre8sADEMZ4GXhd:b-896fix) ([raw file](https://github.com/pmem/miniasync/blob/ec38579167a5ad1ef82f39be096e5d49f8fdb9e8/doc/future_context_get_size.3.md.in#L24)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

combined/total size (?)
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-03-04 13:59 UTC, kswiecicki commented
___
*[doc/future_context_get_size.3.md.in, line 40 at r1](https://reviewable.io/reviews/pmem/miniasync/57#-Mwkp89MDarCaL-7Zwxv:-MxKDdrv0DFDJaq8voTn:b-896fix) ([raw file](https://github.com/pmem/miniasync/blob/ec38579167a5ad1ef82f39be096e5d49f8fdb9e8/doc/future_context_get_size.3.md.in#L40)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

data and output structs (?)
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-03-04 14:00 UTC, kswiecicki commented
___
*[doc/future_poll.3.md.in, line 55 at r1](https://reviewable.io/reviews/pmem/miniasync/57#-MwksCmZEzJ5Eu0v4-im:-MxKDf_O8VBrQmaYQ4Cw:by5jlyf) ([raw file](https://github.com/pmem/miniasync/blob/ec38579167a5ad1ef82f39be096e5d49f8fdb9e8/doc/future_poll.3.md.in#L55)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

what are notifiers exactly? what kind of notifiers do you support? perhaps they are described somewhere...?
</blockquote></details>

I've added an explanation here, take a look.


<!-- Sent from Reviewable.io -->

2022-03-04 14:00 UTC, kswiecicki commented
___
*[doc/future_poll.3.md.in, line 68 at r1](https://reviewable.io/reviews/pmem/miniasync/57#-MwkmpWR8j42jdTvRO5J:-MxKDkNh89UuOTyDzj0v:b-896fix) ([raw file](https://github.com/pmem/miniasync/blob/ec38579167a5ad1ef82f39be096e5d49f8fdb9e8/doc/future_poll.3.md.in#L68)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

`**FF...`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-03-04 14:00 UTC, kswiecicki commented
___
*[doc/miniasync_future.3.md.in, line 44 at r1](https://reviewable.io/reviews/pmem/miniasync/57#-MwkwFdv6jmTmlODKklA:-MxKDlnsEKNnAQIWLkAK:b-896fix) ([raw file](https://github.com/pmem/miniasync/blob/ec38579167a5ad1ef82f39be096e5d49f8fdb9e8/doc/miniasync_future.3.md.in#L44)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

output and busy_poll are not described
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-03-04 14:00 UTC, kswiecicki commented
___
*[doc/miniasync_future.3.md.in, line 65 at r1](https://reviewable.io/reviews/pmem/miniasync/57#-Mwksmws-g0QJ9Aflvq-:-MxKDmtgAnXci1ieYlpy:b-896fix) ([raw file](https://github.com/pmem/miniasync/blob/ec38579167a5ad1ef82f39be096e5d49f8fdb9e8/doc/miniasync_future.3.md.in#L65)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

begin (with?) an ...
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-03-04 14:00 UTC, kswiecicki commented
___
*[doc/miniasync_future.3.md.in, line 68 at r1](https://reviewable.io/reviews/pmem/miniasync/57#-MwksxXD69n5nXTAGTlM:-MxKDo-QCtBV64Qk-zAs:b-3ed9d) ([raw file](https://github.com/pmem/miniasync/blob/ec38579167a5ad1ef82f39be096e5d49f8fdb9e8/doc/miniasync_future.3.md.in#L68)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

did you mean `FUTURE()` - perhaps mention it here...?
</blockquote></details>

I've decided to make a section for all those macros and mention it here.


<!-- Sent from Reviewable.io -->

2022-03-04 14:01 UTC, kswiecicki commented
___
*[doc/miniasync_future.3.md.in, line 110 at r1](https://reviewable.io/reviews/pmem/miniasync/57#-Mwkwk2yEhWw_DRbv_sO:-MxKDxzgDdomgLKKp-XQ:bg6cs1s) ([raw file](https://github.com/pmem/miniasync/blob/ec38579167a5ad1ef82f39be096e5d49f8fdb9e8/doc/miniasync_future.3.md.in#L110)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

based on this description I couldn't figure out that these entries should be a part of the data structure for a FUTURE (maybe it's me, maybe it's the wording)
</blockquote></details>

I've rewritten it, take a look.


<!-- Sent from Reviewable.io -->

2022-03-04 14:01 UTC, kswiecicki commented
___
*[doc/miniasync_future.3.md.in, line 116 at r1](https://reviewable.io/reviews/pmem/miniasync/57#-MwkyfnKBDdB8piQ9wP8:-MxKE42WCi8Z2otRXTvR:b3c0gmu) ([raw file](https://github.com/pmem/miniasync/blob/ec38579167a5ad1ef82f39be096e5d49f8fdb9e8/doc/miniasync_future.3.md.in#L116)):*
<details><summary><i>Previously, pbalcer (Piotr Balcer) wrote…</i></summary><blockquote>

just the future's local state in its own data struct.
</blockquote></details>

I've added an information that all the entries have to be intiialized.


<!-- Sent from Reviewable.io -->

2022-03-04 14:01 UTC, kswiecicki commented
___
*[doc/miniasync_future.3.md.in, line 118 at r1](https://reviewable.io/reviews/pmem/miniasync/57#-MwkyQHB9AW3ZnHTA1-J:-MxKE8p_0J8QhHAj-hiT:b-896fix) ([raw file](https://github.com/pmem/miniasync/blob/ec38579167a5ad1ef82f39be096e5d49f8fdb9e8/doc/miniasync_future.3.md.in#L118)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

`... to start.` or `... to start its execution.`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-03-04 14:02 UTC, kswiecicki commented
___
*[doc/miniasync_future.3.md.in, line 125 at r1](https://reviewable.io/reviews/pmem/miniasync/57#-Mwl6oPpBg3o0cGfrOLy:-MxKE9ix5wh9dXgYnKSf:bavtrqz) ([raw file](https://github.com/pmem/miniasync/blob/ec38579167a5ad1ef82f39be096e5d49f8fdb9e8/doc/miniasync_future.3.md.in#L125)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

something is "no yes" with this description :wink: 
</blockquote></details>

It was a forgotten remnant of copy paste that I've was supposed to change.


<!-- Sent from Reviewable.io -->

2022-03-04 14:03 UTC, kswiecicki commented
___
*[doc/miniasync_future.3.md.in, line 131 at r1](https://reviewable.io/reviews/pmem/miniasync/57#-MwknF2S8vacoSdChyNA:-MxKEP_d8qiU-xm6bp06:b-896fix) ([raw file](https://github.com/pmem/miniasync/blob/ec38579167a5ad1ef82f39be096e5d49f8fdb9e8/doc/miniasync_future.3.md.in#L131)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

\+ add `future_context_get_size`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-03-04 14:04 UTC, kswiecicki commented
___
*[doc/miniasync_runtime.3.md.in, line 79 at r1](https://reviewable.io/reviews/pmem/miniasync/57#-MwkpTc1AjtkjgAgdDrW:-MxKERPO4YdkpgNJRU9v:b-k0uxfm) ([raw file](https://github.com/pmem/miniasync/blob/ec38579167a5ad1ef82f39be096e5d49f8fdb9e8/doc/miniasync_runtime.3.md.in#L79)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

just FYI, you don't have ERRORS section in other manpages
</blockquote></details>

Yeah, I've overlooked it, the error handling will be added in the future.


<!-- Sent from Reviewable.io -->

2022-03-04 14:04 UTC, kswiecicki commented
___
*[doc/miniasync_runtime.3.md.in, line 47 at r1](https://reviewable.io/reviews/pmem/miniasync/57#-MwkqZZ81WZOHsCs2Bd6:-MxKEkso83369rYJo2Dt:b-896fix) ([raw file](https://github.com/pmem/miniasync/blob/ec38579167a5ad1ef82f39be096e5d49f8fdb9e8/doc/miniasync_runtime.3.md.in#L47)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

`context switch` -> `switch context` (or e.g. `do context-switch`)
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-03-04 14:05 UTC, kswiecicki commented
___
*[doc/miniasync_runtime.3.md.in, line 47 at r1](https://reviewable.io/reviews/pmem/miniasync/57#-MwkqmsO9ZyGWn1n3zuf:-MxKElfa7xaZZYLiIQbc:bolzs2n) ([raw file](https://github.com/pmem/miniasync/blob/ec38579167a5ad1ef82f39be096e5d49f8fdb9e8/doc/miniasync_runtime.3.md.in#L47)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

what do you mean "it will switch context"? (between what)
</blockquote></details>

I've written it with more detail now. Take a look.


<!-- Sent from Reviewable.io -->

2022-03-04 14:05 UTC, kswiecicki commented
___
*[doc/miniasync_runtime.3.md.in, line 57 at r1](https://reviewable.io/reviews/pmem/miniasync/57#-MwkrC4w-_wbo8592M0y:-MxKEshVCYGdDeYQ1MLU:b-896fix) ([raw file](https://github.com/pmem/miniasync/blob/ec38579167a5ad1ef82f39be096e5d49f8fdb9e8/doc/miniasync_runtime.3.md.in#L57)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

in repo
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-03-04 14:05 UTC, kswiecicki commented
___
*[doc/miniasync_runtime.7.md, line 37 at r4](https://reviewable.io/reviews/pmem/miniasync/57#-MxF1C-KBpBJL4r7vBFG:-MxKF2Lj3xnV0pYXWwhR:b-896fix) ([raw file](https://github.com/pmem/miniasync/blob/a00119841404be26030b6844880289670ac1984d/doc/miniasync_runtime.7.md#L37)):*
<details><summary><i>Previously, pbalcer (Piotr Balcer) wrote…</i></summary><blockquote>

runtime is specifically not an abstraction. It's an implementation.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-03-04 14:08 UTC, kswiecicki commented
___
*[doc/miniasync_future.3.md.in, line 112 at r1](https://reviewable.io/reviews/pmem/miniasync/57#-Mwl-qdE8IkG3m8i0TZu:-MxKFjxe0mWhQ4PFv5q8:b3c0gmu) ([raw file](https://github.com/pmem/miniasync/blob/ec38579167a5ad1ef82f39be096e5d49f8fdb9e8/doc/miniasync_future.3.md.in#L112)):*
<details><summary><i>Previously, pbalcer (Piotr Balcer) wrote…</i></summary><blockquote>

yes.
</blockquote></details>

I've added an information that all the entries have to be intiialized.


<!-- Sent from Reviewable.io -->

2022-03-04 14:09 UTC, kswiecicki commented
___
*[doc/miniasync_future.3.md.in, line 116 at r1](https://reviewable.io/reviews/pmem/miniasync/57#-MwkyfnKBDdB8piQ9wP8:-MxKFo_1EQiGjAayNaBq:bwhkyfb) ([raw file](https://github.com/pmem/miniasync/blob/ec38579167a5ad1ef82f39be096e5d49f8fdb9e8/doc/miniasync_future.3.md.in#L116)):*
<details><summary><i>Previously, kswiecicki (Krzysztof Święcicki) wrote…</i></summary><blockquote>

I've added an information that all the entries have to be intiialized.
</blockquote></details>

My bad, I've replied to a wrong remark.


<!-- Sent from Reviewable.io -->

2022-03-04 14:09 UTC, kswiecicki commented
___
*[doc/miniasync_runtime.7.md, line 42 at r4](https://reviewable.io/reviews/pmem/miniasync/57#-MxF1S-K5QmDVLu0ZWpI:-MxKG-UR13XAfCs8iEUX:b-896fix) ([raw file](https://github.com/pmem/miniasync/blob/a00119841404be26030b6844880289670ac1984d/doc/miniasync_runtime.7.md#L42)):*
<details><summary><i>Previously, pbalcer (Piotr Balcer) wrote…</i></summary><blockquote>

optimize
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-03-04 14:14 UTC, kswiecicki commented
___
*[doc/miniasync_runtime.7.md, line 43 at r4](https://reviewable.io/reviews/pmem/miniasync/57#-MxF1Zrc0py7uwquxqv8:-MxKG0zXDDN5GvFcabHU:b3dfc61) ([raw file](https://github.com/pmem/miniasync/blob/a00119841404be26030b6844880289670ac1984d/doc/miniasync_runtime.7.md#L43)):*
<details><summary><i>Previously, pbalcer (Piotr Balcer) wrote…</i></summary><blockquote>

`polls each future until no further progress can be made, and then goes to sleep` this is more generic.

Right now the runtime will spin poll each function 1k times before going to sleep. And in the future we might be able to implement something to optimize this more.


</blockquote></details>

I've rewritten it according to your suggestion.


<!-- Sent from Reviewable.io -->

2022-03-04 14:16 UTC, kswiecicki commented
___
*[doc/miniasync_vdm.3.md.in, line 44 at r1](https://reviewable.io/reviews/pmem/miniasync/57#-MwkpmSf3bxWH90vTpZ-:-MxKHCPy7ihXz4MmVKY6:be151xs) ([raw file](https://github.com/pmem/miniasync/blob/ec38579167a5ad1ef82f39be096e5d49f8fdb9e8/doc/miniasync_vdm.3.md.in#L44)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

FYI, you can use CMake's `configure_file` to include the content of an example (like we do this e.g. in pmemkv: https://github.com/pmem/pmemkv/blob/master/doc/libpmemkv_config.3.md.in#L258 )
</blockquote></details>

For now, we have decided to remove `configure_file`, but it's a nice use-case.


<!-- Sent from Reviewable.io -->

2022-03-04 14:17 UTC, kswiecicki commented
___
*[doc/miniasync_vdm_dml.7.md, line 45 at r4](https://reviewable.io/reviews/pmem/miniasync/57#-MxF2Qf22jcf5mc_TFaH:-MxKHeV972FCpXfP5XdV:bc86bur) ([raw file](https://github.com/pmem/miniasync/blob/a00119841404be26030b6844880289670ac1984d/doc/miniasync_vdm_dml.7.md#L45)):*
<details><summary><i>Previously, pbalcer (Piotr Balcer) wrote…</i></summary><blockquote>

DML nor virtual data mover are not "a non-blocking copy operation"
</blockquote></details>

It was an old description, I've rewritten this manpage.


<!-- Sent from Reviewable.io -->

2022-03-04 14:18 UTC, kswiecicki commented
___
*[doc/runtime_new.3.md, line 38 at r1](https://reviewable.io/reviews/pmem/miniasync/57#-MwkpNGj5Hcp82rfdcCp:-MxKHlIvAmsrQ6ZjyCv8:b-rj01zs) ([raw file](https://github.com/pmem/miniasync/blob/ec38579167a5ad1ef82f39be096e5d49f8fdb9e8/doc/runtime_new.3.md#L38)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

`(3)` (?)
</blockquote></details>

The answer to this is in on of the previous replies.


<!-- Sent from Reviewable.io -->

2022-03-04 14:18 UTC, kswiecicki commented
___
*[doc/runtime_wait.3.md, line 50 at r2](https://reviewable.io/reviews/pmem/miniasync/57#-MwlXtrJwgnOq2MZJH1C-r2-50:-MxKHug87HNGV9dmn11o:b-896fix) ([raw file](https://github.com/pmem/miniasync/blob/9d695b7baf412ed5e78af30e59db38d6657ef4a9/doc/runtime_wait.3.md#L50)):*
<details><summary><i>Previously, DamianDuy (Damian Duy) wrote…</i></summary><blockquote>

I think it should be `similar to the`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-03-04 14:20 UTC, kswiecicki commented
> I think we should merge this patch once it's complete, but not necessarily "perfect". Then we can refine the man pages as we go.

I think the PR is sufficient enough, to be opened, take a look.





<!-- Sent from Reviewable.io -->

2022-03-04 15:21 UTC, pbalcer requested changes
> Reviewed 1 of 10 files at r2, 3 of 23 files at r3, 6 of 19 files at r5, 20 of 20 files at r6, 1 of 1 files at r7, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/miniasync/57)* status: all files reviewed, 30 unresolved discussions (waiting on @DamianDuy, @kswiecicki, and @lukaszstolarczuk)

___
*[doc/data_mover_threads_new.3.md, line 56 at r8](https://reviewable.io/reviews/pmem/miniasync/57#-MxKVzlI1X1NMqy1-GCd:-MxKVzlI1X1NMqy1-GCe:bkqyfy5) ([raw file](https://github.com/pmem/miniasync/blob/fbf333097567457f535788888ed6667390e2e2f8/doc/data_mover_threads_new.3.md#L56)):*
> ```Markdown
> Currently, thread data mover supports following notifer types:
> 
> * **FUTURE_NOTIFIER_NONE** - no notifier
> ```

remove the '- no notifier' '- waker'. it serves no purpose.
___
*[doc/miniasync.7.md, line 25 at r8](https://reviewable.io/reviews/pmem/miniasync/57#-MxKThqzCo_CsdSkQFVa:-MxKThqzCo_CsdSkQFVb:b29f2s3) ([raw file](https://github.com/pmem/miniasync/blob/fbf333097567457f535788888ed6667390e2e2f8/doc/miniasync.7.md#L25)):*
> ```Markdown
> # DESCRIPTION #
> 
> **miniasync** is a minimalistic library used for asynchronous programming in C
> ```

This doesn't read great. But let's leave it for now.
___
*[doc/miniasync_future.7.md, line 120 at r8](https://reviewable.io/reviews/pmem/miniasync/57#-MxKUNlB03Fzdc0_0HxE:-MxKUNlB03Fzdc0_0HxF:bg2fr3o) ([raw file](https://github.com/pmem/miniasync/blob/fbf333097567457f535788888ed6667390e2e2f8/doc/miniasync_future.7.md#L120)):*
> ```Markdown
> A waker is a tuple composed of a function pointer and a data context pointer.
> If a waker is supplied and consumed by a future, it will call the provided
> function with its data pointer. The caller needs to make sure that the waker
> ```

will call the function with its data pointer when the future can be polled again to make further progress.
___
*[doc/miniasync_future.7.md, line 150 at r8](https://reviewable.io/reviews/pmem/miniasync/57#-MxKUmCXD9Ay63P5OE1x:-MxKUmCXD9Ay63P5OE1y:blc9nok) ([raw file](https://github.com/pmem/miniasync/blob/fbf333097567457f535788888ed6667390e2e2f8/doc/miniasync_future.7.md#L150)):*
> ```Markdown
> type named *\_name*. Future chain entries should be defined as the members of chained future data structure
> using this macro. Chained future can be composed of multiple future chain entries that will be
> executed sequentially in the order they were defined.
> ```

they are defined.
___
*[doc/miniasync_vdm.7.md, line 39 at r8](https://reviewable.io/reviews/pmem/miniasync/57#-MxKVHdYAmD5X2RkhMd5:-MxKVHdZ7JXsXAcblnrl:bdrp1xj) ([raw file](https://github.com/pmem/miniasync/blob/fbf333097567457f535788888ed6667390e2e2f8/doc/miniasync_vdm.7.md#L39)):*
> ```Markdown
> 
> Virtual data mover API forms the basis of various concrete data movers.
> It is an abstraction that the concrete data mover implementations should adapt
> ```

too much concrete ;)


<!-- Sent from Reviewable.io -->

2022-03-04 15:43 UTC, kswiecicki commented
___
*[doc/data_mover_threads_new.3.md, line 56 at r8](https://reviewable.io/reviews/pmem/miniasync/57#-MxKVzlI1X1NMqy1-GCd:-MxKaTL94ybsNvNMk5Xp:b-896fix) ([raw file](https://github.com/pmem/miniasync/blob/fbf333097567457f535788888ed6667390e2e2f8/doc/data_mover_threads_new.3.md#L56)):*
<details><summary><i>Previously, pbalcer (Piotr Balcer) wrote…</i></summary><blockquote>

remove the '- no notifier' '- waker'. it serves no purpose.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-03-04 15:44 UTC, kswiecicki commented
___
*[doc/miniasync_future.7.md, line 120 at r8](https://reviewable.io/reviews/pmem/miniasync/57#-MxKUNlB03Fzdc0_0HxE:-MxKaWqP93CVULZUtCBD:b-896fix) ([raw file](https://github.com/pmem/miniasync/blob/fbf333097567457f535788888ed6667390e2e2f8/doc/miniasync_future.7.md#L120)):*
<details><summary><i>Previously, pbalcer (Piotr Balcer) wrote…</i></summary><blockquote>

will call the function with its data pointer when the future can be polled again to make further progress.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-03-04 15:44 UTC, kswiecicki commented
___
*[doc/miniasync_future.7.md, line 150 at r8](https://reviewable.io/reviews/pmem/miniasync/57#-MxKUmCXD9Ay63P5OE1x:-MxKaXkT2TMTp1MPNT9q:b-896fix) ([raw file](https://github.com/pmem/miniasync/blob/fbf333097567457f535788888ed6667390e2e2f8/doc/miniasync_future.7.md#L150)):*
<details><summary><i>Previously, pbalcer (Piotr Balcer) wrote…</i></summary><blockquote>

they are defined.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-03-04 15:44 UTC, kswiecicki commented
___
*[doc/miniasync_vdm.7.md, line 39 at r8](https://reviewable.io/reviews/pmem/miniasync/57#-MxKVHdYAmD5X2RkhMd5:-MxKaYkXAvp6JlYM8-9c:b-896fix) ([raw file](https://github.com/pmem/miniasync/blob/fbf333097567457f535788888ed6667390e2e2f8/doc/miniasync_vdm.7.md#L39)):*
<details><summary><i>Previously, pbalcer (Piotr Balcer) wrote…</i></summary><blockquote>

too much concrete ;)
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-03-04 16:48 UTC, lukaszstolarczuk reviewed
Same from my side - few issues, but it looks good in general.

> Reviewed 6 of 19 files at r5, 1 of 20 files at r6, 1 of 1 files at r7, 1 of 1 files at r8, 5 of 9 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/miniasync/57#-:-MxKoyoE8_-RDqqvzz0R:b-e6i15r)* status: 31 of 35 files reviewed, 19 unresolved discussions (waiting on @DamianDuy, @kswiecicki, @lukaszstolarczuk, and @pbalcer)

___
*[doc/miniasync_runtime.7.md, line 4 at r6](https://reviewable.io/reviews/pmem/miniasync/57#-MxKdTJi55xsnDGQl7TM:-MxKdTJi55xsnDGQl7TN:b-7v0lxk) ([raw file](https://github.com/pmem/miniasync/blob/d66a99a8f816da3cced80d69cf682f0febfa5888/doc/miniasync_runtime.7.md#L4)):*
> ```Markdown
> layout: manual
> Content-Style: 'text/css'
> title: _MP(MINIASYNC_RUNTIME, 3)
> ```

`, 7`
___
*[doc/miniasync_runtime.7.md, line 13 at r6](https://reviewable.io/reviews/pmem/miniasync/57#-MxKdURL2TYHkLKEnYH5:-MxKdURL2TYHkLKEnYH6:bb7b55o) ([raw file](https://github.com/pmem/miniasync/blob/d66a99a8f816da3cced80d69cf682f0febfa5888/doc/miniasync_runtime.7.md#L13)):*
> ```Markdown
> [comment]: <> (Copyright 2021-2022, Intel Corporation)
> 
> [comment]: <> (miniasync_runtime.3 -- man page for miniasync runtime API)
> ```

`.7`
___
*[doc/miniasync_runtime.7.md, line 54 at r6](https://reviewable.io/reviews/pmem/miniasync/57#-MxKdhxs0Jdo9pH4t6nL:-MxKdhxs0Jdo9pH4t6nM:b2ngrf9) ([raw file](https://github.com/pmem/miniasync/blob/d66a99a8f816da3cced80d69cf682f0febfa5888/doc/miniasync_runtime.7.md#L54)):*
> ```Markdown
> # SEE ALSO #
> 
> **miniasync_vdm**(3), **miniasync**(7),
> ```

(7)
___
*[doc/miniasync_vdm_threads.7.md, line 4 at r6](https://reviewable.io/reviews/pmem/miniasync/57#-MxKdFCu1JnQprFudXQ0:-MxKdFCu1JnQprFudXQ1:b-7v0lxk) ([raw file](https://github.com/pmem/miniasync/blob/d66a99a8f816da3cced80d69cf682f0febfa5888/doc/miniasync_vdm_threads.7.md#L4)):*
> ```Markdown
> layout: manual
> Content-Style: 'text/css'
> title: _MP(MINIASYNC_VDM_THREADS, 3)
> ```

`, 7`
___
*[doc/miniasync_vdm_threads.7.md, line 13 at r6](https://reviewable.io/reviews/pmem/miniasync/57#-MxKdHru31sePIUA8CWz:-MxKdHru31sePIUA8CX-:b32v7y) ([raw file](https://github.com/pmem/miniasync/blob/d66a99a8f816da3cced80d69cf682f0febfa5888/doc/miniasync_vdm_threads.7.md#L13)):*
> ```Markdown
> [comment]: <> (Copyright 2022, Intel Corporation)
> 
> [comment]: <> (miniasync_vdm_threads.3 -- man page for miniasync vdm threads mover API)
> ```

.7
___
*[extras/dml/README.md, line 9 at r6](https://reviewable.io/reviews/pmem/miniasync/57#-MxKU0be93QR7zbf15J-:-MxKU0be93QR7zbf15J0:br43sm7) ([raw file](https://github.com/pmem/miniasync/blob/d66a99a8f816da3cced80d69cf682f0febfa5888/extras/dml/README.md#L9)):*
> ```Markdown
> 
> **DML** data mover supports offloading certain computations to the hardware
> accelerators (e.g. Intel Data Streaming Accelerator). To use this feature, make
> ```

`Intel®` (?)
___
*[extras/dml/README.md, line 11 at r6](https://reviewable.io/reviews/pmem/miniasync/57#-MxKU6VF1OTUSQpGIlOO:-MxKU6VF1OTUSQpGIlOP:b8lnvhb) ([raw file](https://github.com/pmem/miniasync/blob/d66a99a8f816da3cced80d69cf682f0febfa5888/extras/dml/README.md#L11)):*
> ```Markdown
> accelerators (e.g. Intel Data Streaming Accelerator). To use this feature, make
> sure that **DML** library is compiled with **DML_HW** option.
> For more information about **DML**, see **<https://github.com/intel/DML>**.
> ```

it's an 'md' file, you can use `[...](...)` syntax to generate a proper link
___
*[doc/future_context_get_size.3.md, line 40 at r9](https://reviewable.io/reviews/pmem/miniasync/57#-MxKgpVs6AgYXeGcDXpF:-MxKgpVs6AgYXeGcDXpG:b9mj34j) ([raw file](https://github.com/pmem/miniasync/blob/b0d5b796e285c2b4cef8c31c900da2f7c2ad8451/doc/future_context_get_size.3.md#L40)):*
> ```Markdown
> The **future_context_get_size**() function reads the combined size of the data and output
> structures from the future context *context*. Data structure type and output structure type
> correspond respectively to the *\_data_type* and *\_output_type* parameters that provided
> ```

`that are provided`
___
*[doc/future_poll.3.md, line 46 at r9](https://reviewable.io/reviews/pmem/miniasync/57#-MxKiCwv0FknUqqpruhN:-MxKiCwv0FknUqqpruhO:bwfcrvp) ([raw file](https://github.com/pmem/miniasync/blob/b0d5b796e285c2b4cef8c31c900da2f7c2ad8451/doc/future_poll.3.md#L46)):*
> ```Markdown
> 	uint64_t *ptr_to_monitor;
> };
> ```

aren't these structs now doubled here and in miniasync_future...? you can just leave here an info where to find them (in case they change, you'll have to update only once)
___
*[doc/future_poll.3.md, line 72 at r9](https://reviewable.io/reviews/pmem/miniasync/57#-MxKhIMA0HOZ9WGmCcHT:-MxKhIMA0HOZ9WGmCcHU:bo8fe6c) ([raw file](https://github.com/pmem/miniasync/blob/b0d5b796e285c2b4cef8c31c900da2f7c2ad8451/doc/future_poll.3.md#L72)):*
> ```Markdown
> completion of the task associated with the future pointed by *fut*.
> 
> Additionally, the **future_poll**() function can accept future notifier
> ```

pls add `.` at the end of the sentence :wink: 
___
*[doc/miniasync_future.7.md, line 171 at r9](https://reviewable.io/reviews/pmem/miniasync/57#-MxKmwoB1aXHMJqtz7AZ:-MxKmwoB1aXHMJqtz7A_:bgyqp0q) ([raw file](https://github.com/pmem/miniasync/blob/b0d5b796e285c2b4cef8c31c900da2f7c2ad8451/doc/miniasync_future.7.md#L171)):*
> ```Markdown
> 
> **FUTURE_BUSY_POLL(_futurep)** repeatedly polls the future pointed by *\_futurep* until
> it complete its execution. This macro does not use optimized polling.
> ```

it completes
___
*[doc/miniasync_vdm_dml.7.md, line 45 at r9](https://reviewable.io/reviews/pmem/miniasync/57#-MxKn_j7BBL6mzMdtExO:-MxKn_j7BBL6mzMdtExP:br43sm7) ([raw file](https://github.com/pmem/miniasync/blob/b0d5b796e285c2b4cef8c31c900da2f7c2ad8451/doc/miniasync_vdm_dml.7.md#L45)):*
> ```Markdown
> 
> **DML** data mover supports offloading certain computations to the hardware
> accelerators (e.g. Intel Data Streaming Accelerator) by using **MINIASYNC_DML_F_PATH_HW**
> ```

`Intel®` (?)


<!-- Sent from Reviewable.io -->

2022-03-07 09:21 UTC, kswiecicki commented
___
*[doc/future_context_get_size.3.md, line 40 at r9](https://reviewable.io/reviews/pmem/miniasync/57#-MxKgpVs6AgYXeGcDXpF:-MxYfgGvBtgOuNl8LdX9:b-896fix) ([raw file](https://github.com/pmem/miniasync/blob/b0d5b796e285c2b4cef8c31c900da2f7c2ad8451/doc/future_context_get_size.3.md#L40)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

`that are provided`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-03-07 09:21 UTC, wlemkows requested changes
> Reviewed 3 of 19 files at r5, 7 of 20 files at r6, 1 of 1 files at r7, 1 of 1 files at r8, 8 of 9 files at r9, 1 of 8 files at r10.
> *[Reviewable](https://reviewable.io/reviews/pmem/miniasync/57)* status: 28 of 35 files reviewed, 26 unresolved discussions (waiting on @DamianDuy, @kswiecicki, @lukaszstolarczuk, @pbalcer, and @wlemkows)

___
*[doc/data_mover_sync_get_vdm.3.md, line 31 at r9](https://reviewable.io/reviews/pmem/miniasync/57#-MxYa5fVAiuxElXM21Wc:-MxYa5fVAiuxElXM21Wd:bnsaygv) ([raw file](https://github.com/pmem/miniasync/blob/b0d5b796e285c2b4cef8c31c900da2f7c2ad8451/doc/data_mover_sync_get_vdm.3.md#L31)):*
> ```Markdown
> #include <libminiasync.h>
> 
> struct vdm {
> ```

this structure is not described in the man page
___
*[doc/data_mover_threads_get_vdm.3.md, line 31 at r9](https://reviewable.io/reviews/pmem/miniasync/57#-MxYaRdo5ouSVZDjA8Z-:-MxYaRdo5ouSVZDjA8Z0:b-q2506u) ([raw file](https://github.com/pmem/miniasync/blob/b0d5b796e285c2b4cef8c31c900da2f7c2ad8451/doc/data_mover_threads_get_vdm.3.md#L31)):*
> ```Markdown
> #include <libminiasync.h>
> 
> struct vdm {
> ```

Same here, fields of this structure are magical in this document
___
*[doc/data_mover_threads_new.3.md, line 49 at r9](https://reviewable.io/reviews/pmem/miniasync/57#-MxYWQ3YCWfc6v3FfjAm:-MxYWQ3YCWfc6v3FfjAn:b-xaiuvn) ([raw file](https://github.com/pmem/miniasync/blob/b0d5b796e285c2b4cef8c31c900da2f7c2ad8451/doc/data_mover_threads_new.3.md#L49)):*
> ```Markdown
> 
> # DESCRIPTION #
> ```

Param ringbuf_size is not described.
___
*[doc/data_mover_threads_new.3.md, line 64 at r9](https://reviewable.io/reviews/pmem/miniasync/57#-MxYWhW-6lnfsYcUfmxT:-MxYWhW-6lnfsYcUfmxU:bs8gly1) ([raw file](https://github.com/pmem/miniasync/blob/b0d5b796e285c2b4cef8c31c900da2f7c2ad8451/doc/data_mover_threads_new.3.md#L64)):*
> ```Markdown
> data mover structure pointed by *dms*. Spawned threads are cleaned up during
> finalization.
> ```

data_mover_threads_default is not described



_Code quote:_
```Markdown
data_mover_threads_default
```
___
*[doc/data_mover_threads_new.3.md, line 74 at r9](https://reviewable.io/reviews/pmem/miniasync/57#-MxYWlYJAuVcsSiiRaww:-MxYWlYJAuVcsSiiRawx:b-gcpv7i) ([raw file](https://github.com/pmem/miniasync/blob/b0d5b796e285c2b4cef8c31c900da2f7c2ad8451/doc/data_mover_threads_new.3.md#L74)):*
> ```Markdown
> # SEE ALSO #
> 
> **miniasync**(7), **miniasync_vdm_threads**(7)
> ```

miniasync_future
___
*[doc/future_context_get_output.3.md, line 40 at r9](https://reviewable.io/reviews/pmem/miniasync/57#-MxYfOVHEVcB3VnXN4hP:-MxYfOVHEVcB3VnXN4hQ:bsokojg) ([raw file](https://github.com/pmem/miniasync/blob/b0d5b796e285c2b4cef8c31c900da2f7c2ad8451/doc/future_context_get_output.3.md#L40)):*
> ```Markdown
> The **future_context_get_output**() function reads the output from future context *context*.
> Output type corresponds to the *\_output_type* parameter that is provided to the
> **FUTURE(_name, _data_type, _output_type)** macro during future creation.
> ```

It's too general and abbreviated. List cases or possibly provide a link or example.
___
*[doc/miniasync_vdm_dml.7.md, line 41 at r9](https://reviewable.io/reviews/pmem/miniasync/57#-MxYYdCj4X4lM1qNe7LX:-MxYYdCj4X4lM1qNe7LY:b-unwddj) ([raw file](https://github.com/pmem/miniasync/blob/b0d5b796e285c2b4cef8c31c900da2f7c2ad8451/doc/miniasync_vdm_dml.7.md#L41)):*
> ```Markdown
> 
> **DML** data mover is separated from the primary **miniasync**(7) library. Its encapsulated
> by the **miniasync-vdml-dml**(7) library that has dependency on the **DML** library.
> ```

**miniasync-vdml-dml**(7) ?


<!-- Sent from Reviewable.io -->

2022-03-07 09:25 UTC, kswiecicki commented
___
*[doc/future_poll.3.md, line 46 at r9](https://reviewable.io/reviews/pmem/miniasync/57#-MxKiCwv0FknUqqpruhN:-MxYfjZz3F0c_tBaakIW:b27lb54) ([raw file](https://github.com/pmem/miniasync/blob/b0d5b796e285c2b4cef8c31c900da2f7c2ad8451/doc/future_poll.3.md#L46)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

aren't these structs now doubled here and in miniasync_future...? you can just leave here an info where to find them (in case they change, you'll have to update only once)
</blockquote></details>

I've removed the definitions of those struct.
`For general description of future API, see **miniasync_future**(7).` should point the reader in right direction.



_Code quote:_
```Markdown
For general description of future API, see **miniasync_future**(7).
```


<!-- Sent from Reviewable.io -->

2022-03-07 09:25 UTC, kswiecicki commented
___
*[doc/future_poll.3.md, line 72 at r9](https://reviewable.io/reviews/pmem/miniasync/57#-MxKhIMA0HOZ9WGmCcHT:-MxYghVo4BU-32vE_ceS:b-896fix) ([raw file](https://github.com/pmem/miniasync/blob/b0d5b796e285c2b4cef8c31c900da2f7c2ad8451/doc/future_poll.3.md#L72)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

pls add `.` at the end of the sentence :wink: 
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-03-07 09:25 UTC, kswiecicki commented
___
*[doc/miniasync_future.7.md, line 171 at r9](https://reviewable.io/reviews/pmem/miniasync/57#-MxKmwoB1aXHMJqtz7AZ:-MxYgirp9ZtHfeAHmVws:b-896fix) ([raw file](https://github.com/pmem/miniasync/blob/b0d5b796e285c2b4cef8c31c900da2f7c2ad8451/doc/miniasync_future.7.md#L171)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

it completes
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-03-07 09:25 UTC, kswiecicki commented
___
*[doc/miniasync_runtime.7.md, line 4 at r6](https://reviewable.io/reviews/pmem/miniasync/57#-MxKdTJi55xsnDGQl7TM:-MxYgjsM0fKidl9zvv8S:b-896fix) ([raw file](https://github.com/pmem/miniasync/blob/d66a99a8f816da3cced80d69cf682f0febfa5888/doc/miniasync_runtime.7.md#L4)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

`, 7`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-03-07 10:28 UTC, kswiecicki reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/miniasync/57)* status: 21 of 35 files reviewed, 24 unresolved discussions (waiting on @DamianDuy, @lukaszstolarczuk, @pbalcer, and @wlemkows)

___
*[doc/data_mover_sync_get_vdm.3.md, line 31 at r9](https://reviewable.io/reviews/pmem/miniasync/57#-MxYa5fVAiuxElXM21Wc:-MxYk1YW3DoMUulhsipN:b-hmyyya) ([raw file](https://github.com/pmem/miniasync/blob/b0d5b796e285c2b4cef8c31c900da2f7c2ad8451/doc/data_mover_sync_get_vdm.3.md#L31)):*
<details><summary><i>Previously, wlemkows (Weronika Lewandowska) wrote…</i></summary><blockquote>

this structure is not described in the man page
</blockquote></details>

I've removed it from here and described it in `miniasync_vdm.7.md`.
___
*[doc/data_mover_threads_get_vdm.3.md, line 31 at r9](https://reviewable.io/reviews/pmem/miniasync/57#-MxYaRdo5ouSVZDjA8Z-:-MxYkAfX1POOixAVnueI:blrzyhz) ([raw file](https://github.com/pmem/miniasync/blob/b0d5b796e285c2b4cef8c31c900da2f7c2ad8451/doc/data_mover_threads_get_vdm.3.md#L31)):*
<details><summary><i>Previously, wlemkows (Weronika Lewandowska) wrote…</i></summary><blockquote>

Same here, fields of this structure are magical in this document
</blockquote></details>

Same as in `data_mover_sync_get_vdm.3.md`.
___
*[doc/data_mover_threads_new.3.md, line 49 at r9](https://reviewable.io/reviews/pmem/miniasync/57#-MxYWQ3YCWfc6v3FfjAm:-MxYrnhn9-16zn2q2gMC:b-896fix) ([raw file](https://github.com/pmem/miniasync/blob/b0d5b796e285c2b4cef8c31c900da2f7c2ad8451/doc/data_mover_threads_new.3.md#L49)):*
<details><summary><i>Previously, wlemkows (Weronika Lewandowska) wrote…</i></summary><blockquote>

Param ringbuf_size is not described.
</blockquote></details>

Done.
___
*[doc/data_mover_threads_new.3.md, line 64 at r9](https://reviewable.io/reviews/pmem/miniasync/57#-MxYWhW-6lnfsYcUfmxT:-MxYkym16I5nBhrl9Y63:b-896fix) ([raw file](https://github.com/pmem/miniasync/blob/b0d5b796e285c2b4cef8c31c900da2f7c2ad8451/doc/data_mover_threads_new.3.md#L64)):*
<details><summary><i>Previously, wlemkows (Weronika Lewandowska) wrote…</i></summary><blockquote>

data_mover_threads_default is not described
</blockquote></details>

Done.
___
*[doc/data_mover_threads_new.3.md, line 74 at r9](https://reviewable.io/reviews/pmem/miniasync/57#-MxYWlYJAuVcsSiiRaww:-MxYl43JC5MUS0502iNa:b-896fix) ([raw file](https://github.com/pmem/miniasync/blob/b0d5b796e285c2b4cef8c31c900da2f7c2ad8451/doc/data_mover_threads_new.3.md#L74)):*
<details><summary><i>Previously, wlemkows (Weronika Lewandowska) wrote…</i></summary><blockquote>

miniasync_future
</blockquote></details>

Done.
___
*[doc/miniasync_runtime.7.md, line 13 at r6](https://reviewable.io/reviews/pmem/miniasync/57#-MxKdURL2TYHkLKEnYH5:-MxYgkQaACDEVV9OChkI:b-896fix) ([raw file](https://github.com/pmem/miniasync/blob/d66a99a8f816da3cced80d69cf682f0febfa5888/doc/miniasync_runtime.7.md#L13)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

`.7`
</blockquote></details>

Done.
___
*[doc/miniasync_runtime.7.md, line 54 at r6](https://reviewable.io/reviews/pmem/miniasync/57#-MxKdhxs0Jdo9pH4t6nL:-MxYglSe8AX8xgygVCvz:b-896fix) ([raw file](https://github.com/pmem/miniasync/blob/d66a99a8f816da3cced80d69cf682f0febfa5888/doc/miniasync_runtime.7.md#L54)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

(7)
</blockquote></details>

Done.
___
*[doc/miniasync_vdm_threads.7.md, line 4 at r6](https://reviewable.io/reviews/pmem/miniasync/57#-MxKdFCu1JnQprFudXQ0:-MxYgx7kEE5v48OZLfPM:b-896fix) ([raw file](https://github.com/pmem/miniasync/blob/d66a99a8f816da3cced80d69cf682f0febfa5888/doc/miniasync_vdm_threads.7.md#L4)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

`, 7`
</blockquote></details>

Done.
___
*[doc/miniasync_vdm_threads.7.md, line 13 at r6](https://reviewable.io/reviews/pmem/miniasync/57#-MxKdHru31sePIUA8CWz:-MxYhV0T-c6JzdvVjZBk:b-896fix) ([raw file](https://github.com/pmem/miniasync/blob/d66a99a8f816da3cced80d69cf682f0febfa5888/doc/miniasync_vdm_threads.7.md#L13)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

.7
</blockquote></details>

Done.
___
*[extras/dml/README.md, line 11 at r6](https://reviewable.io/reviews/pmem/miniasync/57#-MxKU6VF1OTUSQpGIlOO:-MxYhXMR3COdZm-lC0Vd:b-896fix) ([raw file](https://github.com/pmem/miniasync/blob/d66a99a8f816da3cced80d69cf682f0febfa5888/extras/dml/README.md#L11)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

it's an 'md' file, you can use `[...](...)` syntax to generate a proper link
</blockquote></details>

Done.
___
*[doc/future_context_get_output.3.md, line 40 at r9](https://reviewable.io/reviews/pmem/miniasync/57#-MxYfOVHEVcB3VnXN4hP:-MxYlih94kM-p6oHYED5:b-896fix) ([raw file](https://github.com/pmem/miniasync/blob/b0d5b796e285c2b4cef8c31c900da2f7c2ad8451/doc/future_context_get_output.3.md#L40)):*
<details><summary><i>Previously, wlemkows (Weronika Lewandowska) wrote…</i></summary><blockquote>

It's too general and abbreviated. List cases or possibly provide a link or example.
</blockquote></details>

Done.
___
*[doc/miniasync_vdm_dml.7.md, line 41 at r9](https://reviewable.io/reviews/pmem/miniasync/57#-MxYYdCj4X4lM1qNe7LX:-MxYgoB-15olvNhUqawI:b-896fix) ([raw file](https://github.com/pmem/miniasync/blob/b0d5b796e285c2b4cef8c31c900da2f7c2ad8451/doc/miniasync_vdm_dml.7.md#L41)):*
<details><summary><i>Previously, wlemkows (Weronika Lewandowska) wrote…</i></summary><blockquote>

**miniasync-vdml-dml**(7) ?
</blockquote></details>

Done.
___
*[doc/miniasync_vdm_dml.7.md, line 45 at r9](https://reviewable.io/reviews/pmem/miniasync/57#-MxKn_j7BBL6mzMdtExO:-MxYgwss4M_hZKcxTUry:b-896fix) ([raw file](https://github.com/pmem/miniasync/blob/b0d5b796e285c2b4cef8c31c900da2f7c2ad8451/doc/miniasync_vdm_dml.7.md#L45)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

`Intel®` (?)
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-03-07 11:00 UTC, pbalcer reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 5 of 8 files at r10, 4 of 9 files at r11.
> *[Reviewable](https://reviewable.io/reviews/pmem/miniasync/57#-:-MxZ1UiX-eKqCZwV-v8S:bnfp4nl)* status: 29 of 35 files reviewed, 19 unresolved discussions (waiting on @DamianDuy, @lukaszstolarczuk, @pbalcer, and @wlemkows)



<!-- Sent from Reviewable.io -->

2022-03-07 11:35 UTC, lukaszstolarczuk reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/miniasync/57)* status: 29 of 35 files reviewed, 10 unresolved discussions (waiting on @DamianDuy, @kswiecicki, @pbalcer, and @wlemkows)

___
*[extras/dml/README.md, line 11 at r11](https://reviewable.io/reviews/pmem/miniasync/57#-MxZ8vcc7sdAX9LIGb0v:-MxZ8vcc7sdAX9LIGb0w:b-4dgrwv) ([raw file](https://github.com/pmem/miniasync/blob/cc15b7826c345b2646b5d39fdccff6a0db7c65e0/extras/dml/README.md#L11)):*
> ```Markdown
> accelerators (e.g. Intel® Data Streaming Accelerator). To use this feature, make
> sure that **DML** library is compiled with **DML_HW** option.
> For more information about **DML**, see [DML](https://github.com/intel/DML>).
> ```

you've left `>` in the link
___
*[doc/miniasync_vdm_dml.7.md, line 60 at r11](https://reviewable.io/reviews/pmem/miniasync/57#-MxZ93uH4Uvb3B1mgqJW:-MxZ93uH4Uvb3B1mgqJX:bobuh1b) ([raw file](https://github.com/pmem/miniasync/blob/cc15b7826c345b2646b5d39fdccff6a0db7c65e0/doc/miniasync_vdm_dml.7.md#L60)):*
> ```Markdown
> * **MINIASYNC_DML_F_MEM_DURABLE** - write to destination is identified as write to durable memory
> 
> * **MINIASYNC_DML_F_PATH_HW** - use hardware accelerators (e.g. Intel Data Streaming Accelerator)
> ```

`Intel®` here as well


<!-- Sent from Reviewable.io -->

2022-03-07 11:44 UTC, kswiecicki reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/miniasync/57)* status: 27 of 35 files reviewed, 10 unresolved discussions (waiting on @DamianDuy, @lukaszstolarczuk, @pbalcer, and @wlemkows)

___
*[extras/dml/README.md, line 11 at r11](https://reviewable.io/reviews/pmem/miniasync/57#-MxZ8vcc7sdAX9LIGb0v:-MxZBMZS3ZcFYfYVwyGU:b-896fix) ([raw file](https://github.com/pmem/miniasync/blob/cc15b7826c345b2646b5d39fdccff6a0db7c65e0/extras/dml/README.md#L11)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

you've left `>` in the link
</blockquote></details>

Done.
___
*[doc/miniasync_vdm_dml.7.md, line 60 at r11](https://reviewable.io/reviews/pmem/miniasync/57#-MxZ93uH4Uvb3B1mgqJW:-MxZBKv7ARkMbPMM2OSE:b-896fix) ([raw file](https://github.com/pmem/miniasync/blob/cc15b7826c345b2646b5d39fdccff6a0db7c65e0/doc/miniasync_vdm_dml.7.md#L60)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

`Intel®` here as well
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-03-07 11:48 UTC, lukaszstolarczuk reviewed
:+1: 

> *[Reviewable](https://reviewable.io/reviews/pmem/miniasync/57#-:-MxZCIoo4DXvNunoIvNC:b-8fx2u7)* status: 27 of 35 files reviewed, 8 unresolved discussions (waiting on @DamianDuy, @pbalcer, and @wlemkows)



<!-- Sent from Reviewable.io -->

2022-03-07 13:15 UTC, wlemkows requested changes
> Reviewed 2 of 19 files at r5, 1 of 20 files at r6, 3 of 8 files at r10, 4 of 9 files at r11.
> *[Reviewable](https://reviewable.io/reviews/pmem/miniasync/57)* status: 31 of 35 files reviewed, 5 unresolved discussions (waiting on @DamianDuy, @kswiecicki, @pbalcer, and @wlemkows)

___
*[doc/data_mover_threads_new.3.md, line 58 at r12](https://reviewable.io/reviews/pmem/miniasync/57#-MxZVuqLA9BGZfSEJ-8Q:-MxZVuqLA9BGZfSEJ-8R:b-xaswbo) ([raw file](https://github.com/pmem/miniasync/blob/bf1a63987b7c4333d1fbffe63e7c53c934c9ecc5/doc/data_mover_threads_new.3.md#L58)):*
> ```Markdown
> 
> The **data_mover_threads_default**() function allocates and initialzied a new thread
> data mover structure with default parameters.
> ```

I think user should also know values of default parameters.


<!-- Sent from Reviewable.io -->

2022-03-07 13:24 UTC, DamianDuy commented on doc/data_mover_threads_new.3.md
> +**data_mover_threads_default**() - allocate, free or allocate with default parameters
The double `allocate` makes it a bit confusing to me. What's the difference between allocate and allocate with default parameters in this case?

2022-03-07 13:26 UTC, wlemkows requested changes
> Reviewed 1 of 8 files at r10, 1 of 9 files at r11, 2 of 2 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/miniasync/57)* status: all files reviewed, 5 unresolved discussions (waiting on @DamianDuy and @kswiecicki)

___
*[doc/miniasync_runtime.7.md, line 38 at r12](https://reviewable.io/reviews/pmem/miniasync/57#-MxZYEBa7K6dcyRBBJSg:-MxZYEBa7K6dcyRBBJSh:b2ngrbt) ([raw file](https://github.com/pmem/miniasync/blob/bf1a63987b7c4333d1fbffe63e7c53c934c9ecc5/doc/miniasync_runtime.7.md#L38)):*
> ```Markdown
> 
> **miniasync**(7) runtime provides methods for efficient polling of single or
> multiple futures, **runtime_wait**(3) and **runtime_wait_multiple** respectively.
> ```

(3)
___
*[doc/miniasync_runtime.7.md, line 55 at r12](https://reviewable.io/reviews/pmem/miniasync/57#-MxZYNoJ2TQjvTft1_Vl:-MxZYNoJ2TQjvTft1_Vm:b9uimoe) ([raw file](https://github.com/pmem/miniasync/blob/bf1a63987b7c4333d1fbffe63e7c53c934c9ecc5/doc/miniasync_runtime.7.md#L55)):*
> ```Markdown
> 
> **miniasync**(7), **miniasync_future**(7),
> **miniasync_vdm**(7) and **<https://pmem.io>**
> ```

update this list


<!-- Sent from Reviewable.io -->

2022-03-07 13:32 UTC, wlemkows reviewed
> Reviewed 1 of 8 files at r10, 2 of 9 files at r11.
> *[Reviewable](https://reviewable.io/reviews/pmem/miniasync/57)* status: all files reviewed, 5 unresolved discussions (waiting on @DamianDuy and @kswiecicki)



<!-- Sent from Reviewable.io -->

2022-03-07 13:33 UTC, DamianDuy commented on doc/data_mover_threads_new.3.md
> +**data_mover_threads_default**() - allocate, free or allocate with default parameters
Okay, never mind, I just got confused. I see that this describes multiple functions now.

2022-03-07 13:48 UTC, DamianDuy commented on doc/miniasync_vdm_dml.7.md
> +**DML** data mover is separated from the primary **miniasync**(7) library. Its encapsulated
`It's` instead of `Its`

2022-03-08 08:03 UTC, kswiecicki reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/miniasync/57)* status: 32 of 35 files reviewed, 6 unresolved discussions (waiting on @DamianDuy, @kswiecicki, and @wlemkows)

___
*[doc/data_mover_threads_new.3.md, line 58 at r12](https://reviewable.io/reviews/pmem/miniasync/57#-MxZVuqLA9BGZfSEJ-8Q:-MxcY6tI94t7a2Fh5zRT:b-896fix) ([raw file](https://github.com/pmem/miniasync/blob/bf1a63987b7c4333d1fbffe63e7c53c934c9ecc5/doc/data_mover_threads_new.3.md#L58)):*
<details><summary><i>Previously, wlemkows (Weronika Lewandowska) wrote…</i></summary><blockquote>

I think user should also know values of default parameters.
</blockquote></details>

Done.
___
*[doc/miniasync_runtime.7.md, line 38 at r12](https://reviewable.io/reviews/pmem/miniasync/57#-MxZYEBa7K6dcyRBBJSg:-MxcYFGa9Nsz-bWGZIA5:b-896fix) ([raw file](https://github.com/pmem/miniasync/blob/bf1a63987b7c4333d1fbffe63e7c53c934c9ecc5/doc/miniasync_runtime.7.md#L38)):*
<details><summary><i>Previously, wlemkows (Weronika Lewandowska) wrote…</i></summary><blockquote>

(3)
</blockquote></details>

Done.
___
*[doc/miniasync_runtime.7.md, line 55 at r12](https://reviewable.io/reviews/pmem/miniasync/57#-MxZYNoJ2TQjvTft1_Vl:-MxcYFZnDWKv0-IRyItr:b-896fix) ([raw file](https://github.com/pmem/miniasync/blob/bf1a63987b7c4333d1fbffe63e7c53c934c9ecc5/doc/miniasync_runtime.7.md#L55)):*
<details><summary><i>Previously, wlemkows (Weronika Lewandowska) wrote…</i></summary><blockquote>

update this list
</blockquote></details>

Done.
___
*[doc/miniasync_vdm_dml.7.md, line 40 at r12](https://reviewable.io/reviews/pmem/miniasync/57#-Mx4U_g7aQPKB0751qtH-r12-40:-MxcYL4t87MqjReLA5iC:b-896fix) ([raw file](https://github.com/pmem/miniasync/blob/bf1a63987b7c4333d1fbffe63e7c53c934c9ecc5/doc/miniasync_vdm_dml.7.md#L40)):*
<details><summary><i>Previously, DamianDuy (Damian Duy) wrote…</i></summary><blockquote>

`It's` instead of `Its`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-03-08 08:12 UTC, wlemkows approved these changes
> Reviewed 3 of 3 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/miniasync/57)* status: all files reviewed, 3 unresolved discussions (waiting on @DamianDuy and @kswiecicki)



<!-- Sent from Reviewable.io -->

2022-03-08 08:14 UTC, merged