common: add package build system
pmem/miniasync pull request #9
Opened 2021-11-17 11:46 UTC by kswiecicki

2021-11-17 12:10 UTC, wlemkows commented
Enable package tests on gha (run-build.sh etc.)
Please look also on package install

2021-11-18 11:48 UTC, kswiecicki commented
I think it works now.

```
Run CPack packaging tool...
CPack: Create package using DEB
CPack: Install projects
CPack: - Run preinstall target for: libuasync
CPack: - Install project: libuasync []
CPack: Create package
-- CPACK_DEBIAN_PACKAGE_DEPENDS not set, the package will have no dependencies.
CPack: - package: /libuasync/build/libuasync-dev-0.0.0_amd64.deb generated.
./libuasync-dev-0.0.0_amd64.deb
./_CPack_Packages/Linux/DEB/libuasync-dev-0.0.0_amd64.deb
$ dpkg-deb --info ./libuasync*.deb
 new Debian package, version 2.0.
 size 576 bytes: control archive=292 bytes.
     226 bytes,     9 lines      control              
       0 bytes,     0 lines      md5sums              
 Architecture: amd64
 Description: C low-level concurrency library for asynchronous functions
 Maintainer: weronika.lewandowska@intel.com
 Package: libuasync-dev
 Priority: optional
 Section: devel
 Version: 0.0.0
 Installed-Size: 4
```





<!-- Sent from Reviewable.io -->

2021-11-19 09:42 UTC, wlemkows commented
@kswiecicki please update README file

2021-11-19 10:32 UTC, wlemkows requested changes

2021-11-19 10:32 UTC, wlemkows commented on CMakeLists.txt
> +set(VERSION_MINOR 0)
9

2021-11-19 10:32 UTC, wlemkows commented on CMakeLists.txt
> +
add also .pc file ad support

2021-11-19 10:32 UTC, wlemkows commented on utils/docker/run-build.sh
> +test_compile_all_examples_standalone
does it works? is this connected to this PR?

2021-11-19 14:59 UTC, kswiecicki commented
___
*[utils/docker/run-build.sh, line 240 at r1](https://reviewable.io/reviews/wlemkows/libuasync/9#-MomoY-CWMMR-l85Ghge-r1-240:-Mosh8LiDwWPvmTx7nG9:bhjrjcc) ([raw file](https://github.com/wlemkows/libuasync/blob/c86b9f617e54b5845412c300ef54a8999ee347e2/utils/docker/run-build.sh#L240)):*
<details><summary><i>Previously, wlemkows (Weronika Lewandowska) wrote…</i></summary><blockquote>

does it work? is this connected to this PR?
</blockquote></details>

It's not related to this PR, I've uncommented this by mistake.


<!-- Sent from Reviewable.io -->

2021-11-19 14:59 UTC, kswiecicki commented
___
*[CMakeLists.txt, line 11 at r1](https://reviewable.io/reviews/wlemkows/libuasync/9#-MohiBIWBIZxJ__aLrU_-r1-11:-MoshMkG6b55er0CM2cL:b-896fix) ([raw file](https://github.com/wlemkows/libuasync/blob/c86b9f617e54b5845412c300ef54a8999ee347e2/CMakeLists.txt#L11)):*
<details><summary><i>Previously, wlemkows (Weronika Lewandowska) wrote…</i></summary><blockquote>

9
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-11-19 15:05 UTC, kswiecicki commented
___
*[CMakeLists.txt, line 11 at r1](https://reviewable.io/reviews/wlemkows/libuasync/9#-MohiBIWBIZxJ__aLrU_-r1-11:-MosidlL2Kjjm2ZGBg3e:bo3sh7d) ([raw file](https://github.com/wlemkows/libuasync/blob/c86b9f617e54b5845412c300ef54a8999ee347e2/CMakeLists.txt#L11)):*
<details><summary><i>Previously, kswiecicki (Krzysztof Święcicki) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Wait, why should it be '9'?


<!-- Sent from Reviewable.io -->

2021-11-19 15:06 UTC, kswiecicki commented
@wlemkows I've updated README to include info about package building.





<!-- Sent from Reviewable.io -->

2021-11-22 13:34 UTC, wlemkows requested changes
> Reviewed 3 of 4 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/wlemkows/libuasync/9)* status: 5 of 8 files reviewed, 2 unresolved discussions (waiting on @kswiecicki and @wlemkows)

___
*[CMakeLists.txt, line 11 at r1](https://reviewable.io/reviews/wlemkows/libuasync/9#-MohiBIWBIZxJ__aLrU_-r1-11:-Mp6puPZ-PbCQoUeHuqD:b-a0gbnc) ([raw file](https://github.com/wlemkows/libuasync/blob/c86b9f617e54b5845412c300ef54a8999ee347e2/CMakeLists.txt#L11)):*
please set
> ```
> set(VERSION_MAJOR 0)
> set(VERSION_MINOR 1)
> set(VERSION_PATCH 0)
> ```
update everywhere (if needed)
___
*[utils/docker/run-build.sh, line 202 at r3](https://reviewable.io/reviews/wlemkows/libuasync/9#-Mp6qeWf8TcKnJ7vw4fr:-Mp6qeWf8TcKnJ7vw4fs:b3kqx) ([raw file](https://github.com/wlemkows/libuasync/blob/bf050f12079ed2f7f6f9955009a3a81db7dcb1e5/utils/docker/run-build.sh#L202)):*
> ```Shell
> #-DTEST_DIR=$TEST_DIR \
> make -j$(nproc)
> ctest --output-on-failure
> ```

.


<!-- Sent from Reviewable.io -->

2021-11-23 09:26 UTC, kswiecicki commented
___
*[CMakeLists.txt, line 11 at r1](https://reviewable.io/reviews/wlemkows/libuasync/9#-MohiBIWBIZxJ__aLrU_-r1-11:-MpB6UWLAOH26-oJdZbE:b-896fix) ([raw file](https://github.com/wlemkows/libuasync/blob/c86b9f617e54b5845412c300ef54a8999ee347e2/CMakeLists.txt#L11)):*
<details><summary><i>Previously, wlemkows (Weronika Lewandowska) wrote…</i></summary><blockquote>

please set
> ```
> set(VERSION_MAJOR 0)
> set(VERSION_MINOR 1)
> set(VERSION_PATCH 0)
> ```
update everywhere (if needed)
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-11-23 09:28 UTC, kswiecicki commented
___
*[utils/docker/run-build.sh, line 202 at r3](https://reviewable.io/reviews/wlemkows/libuasync/9#-Mp6qeWf8TcKnJ7vw4fr:-MpB73HK3lQc_FN9yKQm:b-896fix) ([raw file](https://github.com/wlemkows/libuasync/blob/bf050f12079ed2f7f6f9955009a3a81db7dcb1e5/utils/docker/run-build.sh#L202)):*
<details><summary><i>Previously, wlemkows (Weronika Lewandowska) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-11-24 06:16 UTC, wlemkows reviewed
> Reviewed 1 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/wlemkows/libuasync/9)* status: 4 of 8 files reviewed, all discussions resolved (waiting on @wlemkows)



<!-- Sent from Reviewable.io -->

2021-11-24 06:17 UTC, wlemkows approved these changes
> Reviewed 1 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/wlemkows/libuasync/9)* status: 5 of 8 files reviewed, all discussions resolved (waiting on @wlemkows)



<!-- Sent from Reviewable.io -->

2021-11-25 09:54 UTC, DamianDuy commented on utils/docker/run-build.sh
> +	sudo_password -S make uninstall
I wonder if, since `make uninstall` is used here, shouldn't it, in the main `CMakeLists.txt` file, be added as a custom target.

2021-11-25 10:52 UTC, DamianDuy commented on README.md
> +CMAKE_INSTALL_PREFIX must be set to a destination were packages will be installed
`where` instead of `were`

2021-11-25 11:52 UTC, pbalcer commented
Needs a rebase, otherwise lgtm.

2021-11-25 13:15 UTC, kswiecicki commented
___
*[utils/docker/run-build.sh, line 245 at r4](https://reviewable.io/reviews/pmem/miniasync/9#-MomoY-CWMMR-l85Ghge-r4-245:-MpME1_v-_xfMXxiINX2:buykirf) ([raw file](https://github.com/pmem/miniasync/blob/a4034d43e6f1f14bbafed9e5599f21e69e2a5b23/utils/docker/run-build.sh#L245)):*
<details><summary><i>Previously, DamianDuy (Damian Duy) wrote…</i></summary><blockquote>

I wonder if, since `make uninstall` is used here, shouldn't it, in the main `CMakeLists.txt` file, be added as a custom target.
</blockquote></details>

It's out of scope of this PR, I've left it as a comment.


<!-- Sent from Reviewable.io -->

2021-11-25 13:15 UTC, kswiecicki commented
Rebased.





<!-- Sent from Reviewable.io -->

2021-11-25 13:18 UTC, DamianDuy reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/pmem/miniasync/9#-:-MpMEr_57XdpGMDU3nx9:bnfp4nl)* status: 0 of 9 files reviewed, 1 unresolved discussion (waiting on @DamianDuy, @kswiecicki, and @wlemkows)



<!-- Sent from Reviewable.io -->

2021-11-25 14:12 UTC, pbalcer reviewed
Have you checked if the produced deb and rpm packages actually work?

> Reviewed 8 of 9 files at r5, 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/pmem/miniasync/9#-:-MpMRCPpEIQJY9IeIbEs:b3i3jd8)* status: all files reviewed (commit messages unreviewed), 1 unresolved discussion (waiting on @kswiecicki)



<!-- Sent from Reviewable.io -->

2021-11-25 15:08 UTC, lplewa approved these changes

2021-11-25 15:11 UTC, kswiecicki commented
I've just checked and although an libminiasync is placed in the /usr/lib64 directory, /usr/include doesn't contain libminiasync.h header. I'm currently looking into it.





<!-- Sent from Reviewable.io -->

2021-11-25 16:27 UTC, kswiecicki commented
Packages should be installed correctly now. The libminiasync.h header includes miniasync specific headers though, so if someone includes <libminiasync.h>, he'll get an error about "future.h" not being found and so on.
I think that including those headers in the public header libminiasync.h is a temporary solution and we plan to correct that in the future, is that correct?





<!-- Sent from Reviewable.io -->

2021-11-26 15:07 UTC, pbalcer commented
There should be a directory `miniasync` inside of include that has all the specific include files. And then packages will install both `libminiasync.h` and the directory with those headers. See pmdk for example:
https://github.com/pmem/pmdk/tree/master/src/include

2021-11-29 14:16 UTC, kswiecicki commented
I've taken a look at libpmemobj headers and set up ```miniasync``` to install the include files in ```${CMAKE_INSTALL_INCLUDEDIR}/libminiasync```, so that the ```libminiasync.h``` can find them.
@pbalcer please take a look.





<!-- Sent from Reviewable.io -->

2021-11-29 14:38 UTC, merged